### PR TITLE
Reusable retry script for CI

### PR DESCRIPTION
**Pull request by aaron-siegel**
We occasionally see problems in CI where a job fails due to a transient connectivity issue. This introduces a reusable retry script with the goal of making failure-prone CI steps more robust.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/369)

**Review by anushas — COMMENTED** [review]
LGTM, there's a nit typo in a comment.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/369#-:-OBWmnifAqx_F1q2jZjD:b-e3obu8)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

___
*[`.github/workflows/pytest.yml` line 145 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/369#-OBWmEIH8uCJxKE4ALmM:-OBWmEIH8uCJxKE4ALmN:bxs3jvi) ([raw file](https://github.com/pixeltable/pixeltable/blob/aea694871891de021fff0c2da9c8d6843565a9b5/.github/workflows/pytest.yml#L145)):*
> ```YAML
>             hashFiles('.github/workflows/pytest.yml', 'poetry.lock', 'poetry.toml', 'pyproject.toml', 'Makefile') }}
>       - name: Install the project dependencies
>         # Retry 3 times to be resilient against transitient connectivity issues.
> ```

nit: typo

**Review by anushas — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/369#-:-OBWmxG08-X7PqTxptRj:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/369)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @anushas)

___
*[`.github/workflows/pytest.yml` line 145 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/369#-OBWmEIH8uCJxKE4ALmM:-OBWvx6R6IS3WXzP0jif:busawlc) ([raw file](https://github.com/pixeltable/pixeltable/blob/aea694871891de021fff0c2da9c8d6843565a9b5/.github/workflows/pytest.yml#L145)):*
<details><summary><i>Previously, anushas wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Fixed :)

**Pull request merged**
