### PR TITLE
Standalone Next.JS and FastAPI Application to demonstrate how to use Pixeltable as backend.

### PR DESCRIPTION
**Pull request by pierrebrunelle**
Added it as a folder in the tutorial directory so that it renders the associated README.md correctly.

https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/README.md

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/348)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
Looks nice! I didn't review the typescript code.

Putting this in `docs/` is problematic and that's probably not the right place for it anyway. I'd suggest a top-level `examples/` folder (adjacent to `docs/` and `pixeltable/`) to house this and future fully worked examples.

What editor are you using? There are some random formatting issues (missing newlines at end of file, extra whitespace in blank lines etc) that most of the popular editors (e.g. VSCode) prevent.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/348#-:-OAcTUkI8qCone_CUP0i:bsw8bd6)* status: 0 of 22 files reviewed, 11 unresolved discussions (waiting on @pierrebrunelle)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcU9UdDLa5lId7_XF5):*
What's this file for?
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/.gitignore` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQOhhBlmUEC5NcfGY:-OAcQOhhBlmUEC5NcfGZ:b3bmpbs) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/.gitignore#L1)):*
> ```ignore
> # Dependencies
> ```

We should only have one `.gitignore` file per repo. Delete this file and add any additional exclusions you need to the root `.gitignore`. (Please don't cargo-cult long lists of exclusions - just add the specific ones you need, if any)
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQdDs6rVWR_zWFZse:-OAcQdDs6rVWR_zWFZsf:b-xt2fcx) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L1)):*
> ```Python
> # backend/app.py
> ```

Use "organize imports" in VSCode to put these imports in a canonical order
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 34 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQvWD4Pr80-Qvu_Ui:-OAcQvWD4Pr80-Qvu_Uj:bmjqrgb) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L34)):*
> ```Python
> # Create temp directory
> BASE_DIR = Path(__file__).resolve().parent
> TEMP_DIR = BASE_DIR / "temp_uploads"
> ```

better to use a true temp dir rather than putting this in the repo tree?

```python
import tempfile
TEMP_DIR = tempfile.mkdtemp()
```
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 53 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcRjm_9_n4ZOEhhEPB:-OAcRjm_9_n4ZOEhhEPC:b-1iaoaz) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L53)):*
> ```Python
> video_table = pxt.create_table(
>     'video_search.videos',
>     {'video': pxt.VideoType()}
> ```

use new type syntax:

```python
{'video': pxt.Video}
```
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 73 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcRqbZ5bBNviomsVET:-OAcRqbZ5bBNviomsVEU:b-1va45l) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L73)):*
> ```Python
> async def process_video(file: UploadFile = File(...)):
>     try:
> ```

spurious newline
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 99 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSjZnCSkQmTo2pihf:-OAcSjZnCSkQmTo2pihg:band4kn) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L99)):*
> ```Python
> async def search_video(
>     query: Optional[UploadFile] = File(None),
>     search_type: str = Form(...),
> ```

`search_type: Literal['text', 'image']`
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 122 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSIsE9tmLs_Ow7CwC:-OAcSIsE9tmLs_Ow7CwD:biykbab) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L122)):*
> ```Python
> 
>         # Get results
>         results = frames_view.order_by(sim, asc=False)\
> ```

code style: avoid use of trailing \

```python
results = (
    frames_view.order_by(sim, asc=False)
    .limit(num_results)
    .select(frames_view.frame)
    .collect()
)
```
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 149 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSbaW2cOiF9Lib3tE:-OAcSbaW2cOiF9Lib3tF:bx1w2im) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L149)):*
> ```Python
> if __name__ == "__main__":
>     import uvicorn
>     uvicorn.run(app, host="0.0.0.0", port=8000)
> ```

missing newline at end of file
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/README.md` line 7 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcStu_3HelCRADS0Sf:-OAcStu_3HelCRADS0Sg:b-8ehyne) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/README.md#L7)):*
> ```Markdown
> <a href="https://github.com/pixeltable/pixeltable"></a>
> 
> [Pixeltable](https://github.com/pixeltable/pixeltable) is a declarative interface for working with text, images, embeddings, and even video, enabling you to store, transform, index, and iterate on data.
> ```

no need for the word "even" before "video"

"text, images, embeddings, video, and other media"?
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/requirements.txt` line 36 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcTEMJ0GU6A9RDDg5r:-OAcTEMJ0GU6A9RDDg5s:b6b2ahs) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/requirements.txt#L36)):*
> ```help
> # Optional but recommended for production
> gunicorn==21.2.0
> uvicorn[standard]==0.27.1
> ```

missing newline at end of file (there are a bunch more of these below)

**Review by pierrebrunelle — COMMENTED** [review]
I'll move it to a top-level examples folder. 

I'm using VSCode, maybe I need an extension to clean up the code. I'll check.

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/348#-:-OB2N7_6Eh3-Dc6AHzfV:b-f8xq5x)* status: 0 of 22 files reviewed, 11 unresolved discussions (waiting on @aaron-siegel)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcU9UdDLa5lId7_XF5):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

What's this file for?
</blockquote></details>

I don't know I don't see that file?
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/.gitignore` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQOhhBlmUEC5NcfGY:-OB2PVnhDeudkbFV6wfW:bwxnhi3) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/.gitignore#L1)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We should only have one `.gitignore` file per repo. Delete this file and add any additional exclusions you need to the root `.gitignore`. (Please don't cargo-cult long lists of exclusions - just add the specific ones you need, if any)
</blockquote></details>

Removed .gitignore
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQdDs6rVWR_zWFZse:-OB2PUmT3vst7y-VAi6L:b-896fjx) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L1)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Use "organize imports" in VSCode to put these imports in a canonical order
</blockquote></details>

Done
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 34 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcQvWD4Pr80-Qvu_Ui:-OB2Pu5qD74D7OKW3WYW:b-sr8b51) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L34)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

better to use a true temp dir rather than putting this in the repo tree?

```python
import tempfile
TEMP_DIR = tempfile.mkdtemp()
```
</blockquote></details>

Smart. Thanks. Done.
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 53 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcRjm_9_n4ZOEhhEPB:-OB2RLJVBpdqFTOk2HTj:ba6h8nr) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L53)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

use new type syntax:

```python
{'video': pxt.Video}
```
</blockquote></details>

Not done, I had an error I'll change after.
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 73 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcRqbZ5bBNviomsVET:-OB2RMcnAKFqkUx4Ezvf:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L73)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

spurious newline
</blockquote></details>

Done
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 99 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSjZnCSkQmTo2pihf:-OB2S0xe9fIhXE1RfCUD:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L99)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`search_type: Literal['text', 'image']`
</blockquote></details>

Done
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 122 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSIsE9tmLs_Ow7CwC:-OB2Sf-lBpEe5GYpChLb:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L122)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

code style: avoid use of trailing \

```python
results = (
    frames_view.order_by(sim, asc=False)
    .limit(num_results)
    .select(frames_view.frame)
    .collect()
)
```
</blockquote></details>

Done
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py` line 149 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcSbaW2cOiF9Lib3tE:-OB2SpCK0k5peXrzVCCC:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/app.py#L149)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

missing newline at end of file
</blockquote></details>

Done
___
*[`docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/README.md` line 7 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcStu_3HelCRADS0Sf:-OB2T5g80WA7MTgdRDB8:b-u9kgad) ([raw file](https://github.com/pixeltable/pixeltable/blob/3aaf1344955b55c49d4b6a1d421cbc01a1a661b5/docs/release/tutorials/text-and-image-similarity-search-nextjs-fastapi/README.md#L7)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

no need for the word "even" before "video"

"text, images, embeddings, video, and other media"?
</blockquote></details>

Removed "even"

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/348)* status: 0 of 22 files reviewed, 11 unresolved discussions (waiting on @pierrebrunelle)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/348#-OAcU9UdDLa5lId7_XF5:-OBDZkK51yMfI0XvU7TY:b325y37):*
<details><summary><i>Previously, pierrebrunelle (Pierre Brunelle) wrote…</i></summary><blockquote>

I don't know I don't see that file?
</blockquote></details>

ah it's created by reviewable, my bad

**Pull request merged**
