### PR TITLE
String functions

### PR DESCRIPTION
**Pull request by mkornacker**
Also:
Removed class Predicate and migrated its functionality into Expr, in order to
support general bool expressions in where().

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exprs/expr.py` line 521 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vvL0I04DXa26WYpTk:-O2vvL0I04DXa26WYpTl:b-a7qfdr) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L521)):*
> ```Python
>         raise TypeError(f'Other must be Expr or literal: {type(other)}')
> 
>     def __and__(self, other: object) -> Expr:
> ```

Great! Does this mean boolean expressions can be combined using `and` and `or` as an alternative to `&` and `|`?

If so, I'll update the tutorial as I think this is the most natural set of operators
___
*[`pixeltable/exprs/expr.py` line 541 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vv_kq3P8D8cMRQWB9:-O2vv_kq3P8D8cMRQWBA:b-ie1tw9) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L541)):*
> ```Python
>         return CompoundPredicate(LogicalOperator.NOT, [self])
> 
>     def split_conjuncts(
> ```

Is this intended to be user-facing? If not, precede with a `_`
___
*[`pixeltable/exprs/expr.py` line 542 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vvfOc5Vq8E7QvfmPv:-O2vvfOc5Vq8E7QvfmPw:b-co513m) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L542)):*
> ```Python
> 
>     def split_conjuncts(
>             self, condition: Callable[[Expr], bool]) -> Tuple[List[Expr], Optional[Expr]]:
> ```

Lowercase `list`, `tuple`
___
*[`pixeltable/functions/string.py` line 10 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vwj9e462m_n8w7wrZ:-O2vwj9e462m_n8w7wr_:bioqk8u) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/functions/string.py#L10)):*
> ```Python
> @func.udf
> def capitalize(s: str) -> str:
>     """Equivalent to str.capitalize()"""
> ```

Add proper docstrings for the new UDFs? I'm currently working through adding docstrings for all our existing `pxt.functions` UDFs, and it's a big undertaking; it'd be great not to be digging a new hole

Also add a `string.md` file in `docs/release/api/functions` and a nav entry in `mkdocs.yml`?
___
*[`tests/test_dataframe.py` line 50 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vwICxC7cTTe-g28iW:-O2vwICxC7cTTe-g28iX:b58ax28) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/tests/test_dataframe.py#L50)):*
> ```Python
> 
>         # where clause needs to be a predicate
>         with pytest.raises(excs.Error) as exc_info:
> ```

Also test the other exception (where clause not a Pixeltable expression)?

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232)* status: 0 of 26 files reviewed, 5 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exprs/expr.py` line 521 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vvL0I04DXa26WYpTk:-O34vm8n7-sVHOvPV6FJ:b26qf11) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L521)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Great! Does this mean boolean expressions can be combined using `and` and `or` as an alternative to `&` and `|`?

If so, I'll update the tutorial as I think this is the most natural set of operators
</blockquote></details>

No, this is for & and |. You can't override 'and' and 'or'.
___
*[`pixeltable/exprs/expr.py` line 541 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vv_kq3P8D8cMRQWB9:-O34vrNJ0RRAk04x5sI0:b7dz1pf) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L541)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Is this intended to be user-facing? If not, precede with a `_`
</blockquote></details>

It is, same as when it was part of Predicate.

The user in this case is the planner.
___
*[`pixeltable/exprs/expr.py` line 542 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vvfOc5Vq8E7QvfmPv:-O34wX_vA3W946IEbWOR:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L542)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Lowercase `list`, `tuple`
</blockquote></details>

Done.
___
*[`pixeltable/functions/string.py` line 10 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vwj9e462m_n8w7wrZ:-O34zhYmC6NUxYMOmNTQ:b-gzxg48) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/functions/string.py#L10)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Add proper docstrings for the new UDFs? I'm currently working through adding docstrings for all our existing `pxt.functions` UDFs, and it's a big undertaking; it'd be great not to be digging a new hole

Also add a `string.md` file in `docs/release/api/functions` and a nav entry in `mkdocs.yml`?
</blockquote></details>

Done.

re docstrings: let's discuss if we want to repeat the docstring from str.capitalize()
___
*[`tests/test_dataframe.py` line 50 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vwICxC7cTTe-g28iW:-O34zZFB67PAn8Gu2Yo-:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/tests/test_dataframe.py#L50)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Also test the other exception (where clause not a Pixeltable expression)?
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232)* status: 0 of 28 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/functions/string.py` line 214 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3E-Rod1uU66v_j8y2O:-O3E-Rod1uU66v_j8y2P:b-bf8tyd) ([raw file](https://github.com/pixeltable/pixeltable/blob/e3942b4673865c365028b73bf8bfd72b66be9366/pixeltable/functions/string.py#L214)):*
> ```Python
> 
> @func.udf
> def removeprefix(s: str, prefix: str) -> str:
> ```

I suggest `strip_prefix` and `strip_suffix` here (that'd be consistent with usage in other languages that have these as builtins, such as Rust and Scala)

**Review by aaron-siegel — APPROVED** [review]
Thanks for putting together such comprehensive docs. They look great!

> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232#-:-O3KF9MV20_UioTE0qQK:bzeftth)* status: 0 of 32 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`mkdocs.yml` line 35 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3KF5qmBleHzqjnZrEs:-O3KF5qmBleHzqjnZrEt:b-eltvg1) ([raw file](https://github.com/pixeltable/pixeltable/blob/412a226987fcc0099158573121800e68e5c12571/mkdocs.yml#L35)):*
> ```YAML
>     - Huggingface: api/functions/huggingface.md
>     - StringType: api/functions/string.md
>     - VideoType: api/functions/video.md
> ```

ImageType?
___
*[`pixeltable/exprs/expr.py` line 541 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vv_kq3P8D8cMRQWB9:-O3KEJ6q3_tRwCP2WwW5:boyl9ni) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L541)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It is, same as when it was part of Predicate.

The user in this case is the planner.
</blockquote></details>

Since `Expr` is a user-facing class (in the sense that the user will see tab-completions of it) I'd argue anything non-user-facing should be preceded with a `_`. (The planner is an internal module, not an end user, right?) 
___
*[`pixeltable/functions/image.py` line 2 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3KEcYR3A_JQnLgYyxr:-O3KEcYR3A_JQnLgYyxs:bd2ndz8) ([raw file](https://github.com/pixeltable/pixeltable/blob/412a226987fcc0099158573121800e68e5c12571/pixeltable/functions/image.py#L2)):*
> ```Python
> """
> A collection of Pixeltable [UDFs](https://pixeltable.readme.io/docs/user-defined-functions-udfs) for `ImageType`.
> ```

The verbiage "A collection of" isn't really necessary here (every module is a collection of stuff)

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/232)* status: 0 of 32 files reviewed, 3 unresolved discussions (waiting on @aaron-siegel)

___
*[`mkdocs.yml` line 35 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3KF5qmBleHzqjnZrEs:-O3KNDOI9ashintMzp9a:bqmig9u) ([raw file](https://github.com/pixeltable/pixeltable/blob/412a226987fcc0099158573121800e68e5c12571/mkdocs.yml#L35)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

ImageType?
</blockquote></details>

out of scope
___
*[`pixeltable/exprs/expr.py` line 541 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O2vv_kq3P8D8cMRQWB9:-O3KNFp42bGQtyYGSgve:bdk5bxi) ([raw file](https://github.com/pixeltable/pixeltable/blob/3ee1a2c9f666d880566bd8fa70b8c983fcd75648/pixeltable/exprs/expr.py#L541)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Since `Expr` is a user-facing class (in the sense that the user will see tab-completions of it) I'd argue anything non-user-facing should be preceded with a `_`. (The planner is an internal module, not an end user, right?)
</blockquote></details>

Out of scope for this docs change.
___
*[`pixeltable/functions/image.py` line 2 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3KEcYR3A_JQnLgYyxr:-O3KNIo14LXWEVsstDAI:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/412a226987fcc0099158573121800e68e5c12571/pixeltable/functions/image.py#L2)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The verbiage "A collection of" isn't really necessary here (every module is a collection of stuff)
</blockquote></details>

Done.
___
*[`pixeltable/functions/string.py` line 214 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/232#-O3E-Rod1uU66v_j8y2O:-O3KNVBf3WD3AiQFnFuZ:bxzoi51) ([raw file](https://github.com/pixeltable/pixeltable/blob/e3942b4673865c365028b73bf8bfd72b66be9366/pixeltable/functions/string.py#L214)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I suggest `strip_prefix` and `strip_suffix` here (that'd be consistent with usage in other languages that have these as builtins, such as Rust and Scala)
</blockquote></details>

Mimicking pandas here, as discussed.

**Pull request merged**
