### PR TITLE
Adds draw_bounding_boxes() udf

### PR DESCRIPTION
**Pull request by mkornacker**
Also: renamed functions.eval to functions.vision

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 6 files reviewed, 14 unresolved discussions (waiting on @mkornacker)

___
*[`mkdocs.yml` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtMV64E_kzdF6ROz8:-O4qtMV64E_kzdF6ROz9:brgpd3c) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/mkdocs.yml#L38)):*
> ```YAML
>     - timestamp: api/functions/timestamp.md
>     - video: api/functions/video.md
>     - Computer Vision: api/functions/vision.md
> ```

This should be in a separate category from the basic operations, right?
___
*[`tests/functions/test_functions.py` line 9 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r0-RV6kc2Ilul64cB:-O4r0-RV6kc2Ilul64cC:bfkn9rd) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L9)):*
> ```Python
> 
> class TestFunctions:
>     def test_vision(self, reset_db) -> None:
> ```

This should be moved into a `test/functions/vision.py` file analogous to the other functions tests (and probably broken into several tests; I'm not convinced eval_detections and draw_bounding_boxes belong together)
___
*[`tests/functions/test_functions.py` line 42 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-raE1V_AUCH6rqVe:-O4r-raE1V_AUCH6rqVf:b-w8fzv0) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L42)):*
> ```Python
>         _ = v.select(mean_ap(v.eval_a)).show()[0, 0]
>         _ = v.select(mean_ap(v.eval_b)).show()[0, 0]
>         _ = v.select(draw_bounding_boxes(v.frame_s, boxes=v.detections_a.bboxes, labels=v.detections_a.labels)).collect()
> ```

- Test all parameters
- Test error messages
___
*[`tests/functions/test_functions.py` line 43 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-wU72xV0GHyLu6wW:-O4r-wU72xV0GHyLu6wX:bvyynjg) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L43)):*
> ```Python
>         _ = v.select(mean_ap(v.eval_b)).show()[0, 0]
>         _ = v.select(draw_bounding_boxes(v.frame_s, boxes=v.detections_a.bboxes, labels=v.detections_a.labels)).collect()
>         pass
> ```

Spurious `pass`
___
*[`pixeltable/functions/vision.py` line 32 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtUmo1SL3um-QDru1:-O4qtUmo1SL3um-QDru2:b6dzmq1) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L32)):*
> ```Python
> # (sources at https://github.com/open-mmlab/mmeval)
> # Copyright (c) OpenMMLab. All rights reserved.
> def _calculate_bboxes_area(bboxes: np.ndarray) -> np.ndarray:
> ```

Standard Python convention is to use a double underscore for private methods as in
```
def __calculate_bboxes_area(...)
```
Single underscore is for protected methods that are intended to be part of a class inheritance pattern.

As long as we're updating the codebase, I think we should follow this convention
___
*[`pixeltable/functions/vision.py` line 259 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4quCfK17i_mmZG_aUi:-O4qu0qK6RQfKdq--Oyn:b2gqm3v) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L259)):*
> ```Python
>         color: Optional[str] = None,
>         label_colors: Optional[dict[Union[str, int], str]] = None,
>         box_colors: Optional[list[str]] = None,
> ```

`color` and `box_colors` is weirdly inconsistent nomenclature. Why not `box_color` and `box_colors`?

But best would be a single `Optional[Union[str, list[str]]]` parameter, which will work just fine once `JsonType` is a supertype of `StringType`.

Proposal: just use a single parameter with `list[str]` type for now, then generalize it later when we improve the type hierarchy. Having two separate parameters here feels like we're setting up a quite cluttered API.
___
*[`pixeltable/functions/vision.py` line 260 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qw0ZAEaBeGCaVTnrj:-O4qw0ZAEaBeGCaVTnrk:bq90j7k) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L260)):*
> ```Python
>         label_colors: Optional[dict[Union[str, int], str]] = None,
>         box_colors: Optional[list[str]] = None,
>         fill: Optional[bool]  = False,
> ```

Why is this `Optional`? Isn't it just a straight-up boolean?
___
*[`pixeltable/functions/vision.py` line 263 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qwBGL4_ahut84DUJa:-O4qwBGL4_ahut84DUJb:bqnjhsn) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L263)):*
> ```Python
>         width: int = 1,
>         font: Optional[str] = None,
>         font_size: Optional[int] = None,
> ```

Why not
```
font_size: int = 10
```
?
___
*[`pixeltable/functions/vision.py` line 269 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-D0HDt4-96VzVWwU:-O4r-D0HDt4-96VzVWwV:b-cvsqac) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L269)):*
> ```Python
> 
>     Labels can be either strings or ints (category ids).
>     Colors can be specified as strings (e.g., 'red') or as RGB hex codes (e.g., '#FF0000').
> ```

The docstring would benefit from some more explanation here: there are three ways to specify colors, here's how they behave, etc. Also, how are the names resolved? A link to the `ImageColor.getrgb()` docs would be worthwhile
___
*[`pixeltable/functions/vision.py` line 280 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qw51sDzqBznxZ3Uax:-O4qw51sDzqBznxZ3Uay:b-rdh4tr) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L280)):*
> ```Python
>         fill: Whether to fill the bounding boxes with color.
>         width: Width of the bounding box borders.
>         font: Path to a TrueType font file.
> ```

Mention what happens if it's not specified. Also, does it have to be a path, or can it be the symbolic name of a font installed by the O
___
*[`pixeltable/functions/vision.py` line 295 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzD8j0g8tYMuAdlqL:-O4qzD8kBnnZmklwJrZQ:b-tm5irj) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L295)):*
> ```Python
>         labels = [None] * num_boxes
>     elif len(labels) != num_boxes:
>         raise ValueError("Number of boxes and labels must match")
> ```

Why the sudden use of double quotes? We've standardized on single quotes throughout the codebase.
___
*[`pixeltable/functions/vision.py` line 304 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzLda4x354giYMjGv:-O4qx0Y0-PKQmzMML1q_:b-a0xnvr) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L304)):*
> ```Python
>             box_colors = [color] * num_boxes
>         elif label_colors is not None:
>             box_colors = [label_colors.get(label, "red") for label in labels]
> ```

I propose "gray" as the default for unspecified colors (that's what label studio does in this situation)
___
*[`pixeltable/functions/vision.py` line 306 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qxMyhCXja7jpCsZHX:-O4qxMyhCXja7jpCsZHY:bd8zmmr) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L306)):*
> ```Python
>             box_colors = [label_colors.get(label, "red") for label in labels]
>         else:
>             box_colors = ["red"] * num_boxes
> ```

We could implement a more useful default here without a lot of effort. Somewhere above, add something like this:
```
if label_colors is None and labels is not None:
    distinct_labels = {label: None for label in labels}  # Use a dict for order preservation
    colors = DEFAULT_COLORS * (len(distinct_labels) / len(DEFAULT_COLORS) + 1)
    label_colors = dict(zip(distinct_labels.keys(), colors))
```
where
```
DEFAULT_COLORS = ['red', 'green', 'blue', 'yellow', 'orange', 'purple']
```
or some such.
___
*[`pixeltable/functions/vision.py` line 331 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzdLV9VzEaz8sVVLm:-O4qzdLV9VzEaz8sVVLn:b-azm64d) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L331)):*
> ```Python
>         if label is not None:
>             if not isinstance(label, str):
>                 label = f'Category {label}'
> ```

Why not just use the integer? I'm not sure what the word "Category" adds here.

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @aaron-siegel)

___
*[`mkdocs.yml` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtMV64E_kzdF6ROz8:-O4rEMAl3tYvrP7PHIoB:b-2qbe5u) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/mkdocs.yml#L38)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should be in a separate category from the basic operations, right?
</blockquote></details>

Yeah, maybe. I wasn't sure what to call it. It's not really a 'vertical'. Applications?
___
*[`tests/functions/test_functions.py` line 9 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r0-RV6kc2Ilul64cB:-O4rP91ZDc1xV3nqDvS0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L9)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should be moved into a `test/functions/vision.py` file analogous to the other functions tests (and probably broken into several tests; I'm not convinced eval_detections and draw_bounding_boxes belong together)
</blockquote></details>

Done.
___
*[`tests/functions/test_functions.py` line 42 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-raE1V_AUCH6rqVe:-O4uonHe3AGggEQmupnA:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L42)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

- Test all parameters
- Test error messages
</blockquote></details>

Done.
___
*[`tests/functions/test_functions.py` line 43 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-wU72xV0GHyLu6wW:-O4uonfH7ba8xWdPrrlr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/tests/functions/test_functions.py#L43)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Spurious `pass`
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 32 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtUmo1SL3um-QDru1:-O4rF27QCFoQNRqpDH23:bnikgaf) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L32)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Standard Python convention is to use a double underscore for private methods as in
```
def __calculate_bboxes_area(...)
```
Single underscore is for protected methods that are intended to be part of a class inheritance pattern.

As long as we're updating the codebase, I think we should follow this convention
</blockquote></details>

mkdocs ignore single underscore but not double.
___
*[`pixeltable/functions/vision.py` line 259 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4quCfK17i_mmZG_aUi:-O4rF6aJ5dqyMckt7qao:b-1d3n3y) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L259)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`color` and `box_colors` is weirdly inconsistent nomenclature. Why not `box_color` and `box_colors`?

But best would be a single `Optional[Union[str, list[str]]]` parameter, which will work just fine once `JsonType` is a supertype of `StringType`.

Proposal: just use a single parameter with `list[str]` type for now, then generalize it later when we improve the type hierarchy. Having two separate parameters here feels like we're setting up a quite cluttered API.
</blockquote></details>

I think this is easier. But we can ask the Obvio people for feedback.
___
*[`pixeltable/functions/vision.py` line 260 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qw0ZAEaBeGCaVTnrj:-O4rIbMr5aC2LnnEt4pY:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L260)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why is this `Optional`? Isn't it just a straight-up boolean?
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 263 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qwBGL4_ahut84DUJa:-O4rIcEcCr5B4ZamstVu:b5fcxmd) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L263)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why not
```
font_size: int = 10
```
?
</blockquote></details>

Updated comment
___
*[`pixeltable/functions/vision.py` line 269 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4r-D0HDt4-96VzVWwU:-O4rLKkr8bamzUe4VJAx:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L269)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The docstring would benefit from some more explanation here: there are three ways to specify colors, here's how they behave, etc. Also, how are the names resolved? A link to the `ImageColor.getrgb()` docs would be worthwhile
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 280 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qw51sDzqBznxZ3Uax:-O4rJryA-ipFvXek26fR:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L280)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Mention what happens if it's not specified. Also, does it have to be a path, or can it be the symbolic name of a font installed by the O
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 295 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzD8j0g8tYMuAdlqL:-O4rLGzlEqQlHw-KoKDf:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L295)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why the sudden use of double quotes? We've standardized on single quotes throughout the codebase.
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 304 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzLda4x354giYMjGv:-O4uov0R1P_YD1b0wrMQ:bu8b7f1) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L304)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I propose "gray" as the default for unspecified colors (that's what label studio does in this situation)
</blockquote></details>

I'll use white for higher contrast. We could make that a config parameter.
___
*[`pixeltable/functions/vision.py` line 306 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qxMyhCXja7jpCsZHX:-O4uoqHl5ETEHJlamXd9:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L306)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

We could implement a more useful default here without a lot of effort. Somewhere above, add something like this:
```
if label_colors is None and labels is not None:
    distinct_labels = {label: None for label in labels}  # Use a dict for order preservation
    colors = DEFAULT_COLORS * (len(distinct_labels) / len(DEFAULT_COLORS) + 1)
    label_colors = dict(zip(distinct_labels.keys(), colors))
```
where
```
DEFAULT_COLORS = ['red', 'green', 'blue', 'yellow', 'orange', 'purple']
```
or some such.
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 331 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzdLV9VzEaz8sVVLm:-O4rKFAq6oedqYzQlbr8:b-3h18si) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L331)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why not just use the integer? I'm not sure what the word "Category" adds here.
</blockquote></details>

It's really hard to see when it's just "1".

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`mkdocs.yml` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtMV64E_kzdF6ROz8:-O4vbRpU79x-egHiEVp3:bp5u3pv) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/mkdocs.yml#L38)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Yeah, maybe. I wasn't sure what to call it. It's not really a 'vertical'. Applications?
</blockquote></details>

Sure, "Applications" or "Use Cases" or something like that.
___
*[`pixeltable/functions/vision.py` line 32 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtUmo1SL3um-QDru1:-O4vazxJ5sU5oLoDyVBS:be8pa2n) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L32)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

mkdocs ignore single underscore but not double.
</blockquote></details>

It's just a mkdocs configuration thing. Add
```
filters: ["!^_"]
```
under `plugins/mkdocstrings/handlers/python/options` in `mkdocs.yml`. Note this will suppress dunder methods too (like `__getitem__`); if we want to include those, make it
```
filters: ["!^_", "^__.*__$"]
```
instead.
___
*[`pixeltable/functions/vision.py` line 331 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qzdLV9VzEaz8sVVLm:-O4vbm6F8uMukT3Kjg4w:b-inp4h9) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L331)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It's really hard to see when it's just "1".
</blockquote></details>

Ok... seems like it's easy enough for users to format their own custom text, but i guess it's fine
___
*[`pixeltable/functions/vision.py` line 324 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4vbb336-vLznlzdYOp:-O4vbb336-vLznlzdYOq:b-vooeig) ([raw file](https://github.com/pixeltable/pixeltable/blob/3e44027f68f463a48adf4a7d657e10f3a3715189/pixeltable/functions/vision.py#L324)):*
> ```Python
>         raise ValueError('Number of boxes and labels must match')
> 
>     DEFAULT_COLOR = 'red'
> ```

make this `'white'` to match unlabeled color?

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @aaron-siegel)

___
*[`mkdocs.yml` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtMV64E_kzdF6ROz8:-O4wGmlG2MIGbHdLp7cQ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/mkdocs.yml#L38)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Sure, "Applications" or "Use Cases" or something like that.
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 32 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4qtUmo1SL3um-QDru1:-O4wHVdP4wd0TvYxZJac:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/44e4c770e8ff624789d664d20f08cf21cac5c387/pixeltable/functions/vision.py#L32)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It's just a mkdocs configuration thing. Add
```
filters: ["!^_"]
```
under `plugins/mkdocstrings/handlers/python/options` in `mkdocs.yml`. Note this will suppress dunder methods too (like `__getitem__`); if we want to include those, make it
```
filters: ["!^_", "^__.*__$"]
```
instead.
</blockquote></details>

Done.
___
*[`pixeltable/functions/vision.py` line 324 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4vbb336-vLznlzdYOp:-O4wHaCQ7eE4k4sBbO7r:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3e44027f68f463a48adf4a7d657e10f3a3715189/pixeltable/functions/vision.py#L324)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

make this `'white'` to match unlabeled color?
</blockquote></details>

Done.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`tests/functions/test_vision.py` line 100 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4wcbjm8ycm-hEqrsMs:-O4wcbjm8ycm-hEqrsMt:bhjvhxf) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ce2ab3a110012074758741545563db2e42946c2/tests/functions/test_vision.py#L100)):*
> ```Python
>         assert 'number of boxes and box colors must match' in str(exc_info.value).lower()
> 
>         # font and font_size parameters: they can't be tested in a system-independent way, because the font is a
> ```

In theory they could, either
- check a font file into `tests/data` and refer to that, or
- use a font name such as `Arial` that all testing systems are likely recognize (see preceding comment - PIL looks for files in the system font folders, with the extension implied, so you can just give it the name of a system font)
___
*[`pixeltable/functions/vision.py` line 304 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4wdf1jB8W_PHIGBI3T:-O4wdf1jB8W_PHIGBI3U:b8pfirw) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ce2ab3a110012074758741545563db2e42946c2/pixeltable/functions/vision.py#L304)):*
> ```Python
>         fill: Whether to fill the bounding boxes with color.
>         width: Width of the bounding box borders.
>         font: Path to a TrueType font file, as required by
> ```

Change this to "Name of a system font or path to a TrueType file"

That's what the PIL docs are implying, and I just tried
```
PIL.ImageFont.truetype('Arial')
```
and it worked on my system.  It would likely work for a unit test as well (see my comment below)

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/259)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/functions/vision.py` line 304 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/259#-O4wdf1jB8W_PHIGBI3T:-O4xZkRdDat1eZymwTZZ:b9w7b10) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ce2ab3a110012074758741545563db2e42946c2/pixeltable/functions/vision.py#L304)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Change this to "Name of a system font or path to a TrueType file"

That's what the PIL docs are implying, and I just tried
```
PIL.ImageFont.truetype('Arial')
```
and it worked on my system.  It would likely work for a unit test as well (see my comment below)
</blockquote></details>

I just tried that on my Ubuntu system and got a 'cannot locate resource' error. Leaving a todo for the test.

**Pull request merged**
