### PR TITLE
Various API changes

### PR DESCRIPTION
**Pull request by aaron-siegel**
First set of planned API changes. None of these changes are expected to have user impact (either because they're non-breaking, or they affect features that are not in widespread use).

- Add separate `t.add_computed_column()` API
- Add `t.add_columns()` API for adding multiple columns
- Disallow direct use of a `Callable` in `add_computed_column()` (using a UDF or `apply` is suitable in most cases)
- Use `on_error` instead of `fail_on_exception` in `insert()`
- Add separate `pxt.create_snapshot()` API
- Remove explicit `return_type` and `param_types` parameters from `@udf` decorator (these are obviated by the new type hint system)
- Update notebooks and markdown files to reflect new best practices

These related changes are NOT part of this PR and will be deferred, since they are breaking:

- Disallow `__setitem__()` syntax to add columns
- Disallow use of `add_column()` to add computed columns
- Disallow use of `create_view()` to create snapshots

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/351)

**Comment by pierrebrunelle** [comment]
``Disallow use of create_view() to create snapshots``

I thought we said we would keep that as well, for now, as create_snapshot remains simply a shortcut to create_view(.... snapshot=True)?

**Comment by aaron-siegel** [comment]
> `Disallow use of create_view() to create snapshots`
> 
> I thought we said we would keep that as well, for now, as create_snapshot remains simply a shortcut to create_view(.... snapshot=True)?

That's right, that's why it's not part of this PR

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/351)* status: 0 of 39 files reviewed, 8 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/api/pixeltable.md` line 16 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAi-fjE1tXCqSuN-087:-OAi-fjE1tXCqSuN-088:b-r1fvb6) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/docs/release/api/pixeltable.md#L16)):*
> ```Markdown
> | Table Operations                              |                                 |
> |-----------------------------------------------|---------------------------------|
> | [`pxt.create_table`][pixeltable.create_table] | Create a new (insertable) table |
> ```

Also add an entry here
___
*[`pixeltable/globals.py` line 127 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAi0LKvEMsFfcv5GeEJ:-OAi0LKvEMsFfcv5GeEK:blhjzjc) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/globals.py#L127)):*
> ```Python
>             of the `additional_columns` parameter is identical to the format of the `schema_or_df` parameter in
>             [`create_table`][pixeltable.create_table].
>         is_snapshot: If `True`, create a snapshot instead (see [`create_snapshot`][pixeltable.create_snapshot]).
> ```

I prefer the previous phrasing. We shouldn't give the impression that snapshots are something completely different.
___
*[`pixeltable/globals.py` line 196 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAi0kJSEznqKs2JhqK_:-OAi0kJSEznqKs2JhqKa:bfg95jw) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/globals.py#L196)):*
> ```Python
>     base: Union[catalog.Table, DataFrame],
>     *,
>     additional_columns: Optional[dict[str, Any]] = None,
> ```

It also needs the iterator parameter.
___
*[`pixeltable/catalog/table.py` line 424 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAi2PV_4JyZgf30b5Ng:-OAi2PV_4JyZgf30b5Nh:b-aeyjkk) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/catalog/table.py#L424)):*
> ```Python
> 
>         col_schema: dict[str, Any] = {}
>         if isinstance(spec, (ts.ColumnType, builtins.type, _GenericAlias)):
> ```

Didn't we decide not to allow Python types in schema specs?
___
*[`pixeltable/catalog/table.py` line 543 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAiaVi8BI5zBJDFQCIv:-OAiaVi8BI5zBJDFQCIw:b-ga5rnf) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/catalog/table.py#L543)):*
> ```Python
>                 primary_key = spec.get('primary_key')
>             else:
>                 raise excs.Error(f'Invalid value for column {name!r}')
> ```

Isn't this an internal error? Maybe just assert False?
___
*[`pixeltable/catalog/table.py` line 842 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAibo6N6TxBNWrzWV_j:-OAibo6N6TxBNWrzWV_k:b-vwd42e) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/catalog/table.py#L842)):*
> ```Python
>                 invalid media file (such as a corrupt image) for one of the inserted rows.
> 
>                 - If `on_error='abort'`, then an exception will be raised and the rows will not be inserted.
> ```

For the sake of uniformity, let's go with the less redundant formatting used in Table.batch_update() (if_exists) or create_table() (media_validation):
- `'abort'`: Raise ...
___
*[`tests/test_exprs.py` line 244 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAid9eP4bsYupaZEisx:-OAid9eP4bsYupaZEisy:b8iv229) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa8c653a56ac8a3d3d08b95d33b8d1c3300d2b59/tests/test_exprs.py#L244)):*
> ```Python
> 
>         # computed column that doesn't allow nulls
>         t.add_column(c3=lambda c1, c2: c1 + c2, type=pxt.Required[pxt.Float])
> ```

We want to keep this test case. You need to add a new udf to replace the lambda.
___
*[`tests/test_snapshot.py` line 136 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAie34NBL-_36k6iwAY:-OAie34NBL-_36k6iwAZ:b-f9d41h) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/tests/test_snapshot.py#L136)):*
> ```Python
>         assert status.num_rows == len(rows)
>         assert status.num_excs == 0
>         s1 = pxt.create_snapshot('s1', t)
> ```

Let's leave some create_view(is_snapshot=True) in place to make sure we still test that.

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/351)* status: 0 of 44 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel)

___
*[`tests/test_exprs.py` line 244 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAid9eP4bsYupaZEisx:-OBCNR-sCq1u9ZdiyWtk:btt4aka) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa8c653a56ac8a3d3d08b95d33b8d1c3300d2b59/tests/test_exprs.py#L244)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It's already tested with the `null_args_fn` UDF, right? What is the specific behavior you're trying to capture that's not captured by that example? (Note that UDFs treat null args in a subtly different way from the old inline callables...)
</blockquote></details>

You mean because null_args_fn has one non-opt parameter? True, but the lambda tests one more scenario, which is still useful to validate (the handling of parameter lists with no optionals vs those with some optionals might diverge in the future).
___
*[`docs/release/howto/working-with-external-files.ipynb` line 515 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OBCP63sDQT4TrhRADXB:-OBCP63sDQT4TrhRADXC:b-b8jq80) ([raw file](https://github.com/pixeltable/pixeltable/blob/468cb2a4f37267956617625daf0ad76119858bae/docs/release/howto/working-with-external-files.ipynb#L515)):*
> ```
>    "metadata": {},
>    "source": [
>     "Alternatively, Pixeltable can also be instructed to record error conditions and proceed with the ingest, via the `on_error` flag (default: `'abort'`):"
> ```

It looks like there are a bunch more references to fail_on_exception in the cell output (stack traces). Would be good to re-run this notebook to get rid of these references.

**Review by mkornacker — APPROVED** [review]

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/351)* status: 0 of 44 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`docs/release/howto/working-with-external-files.ipynb` line 515 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OBCP63sDQT4TrhRADXB:-OBD0X6728i46APm_cFm:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/468cb2a4f37267956617625daf0ad76119858bae/docs/release/howto/working-with-external-files.ipynb#L515)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It looks like there are a bunch more references to fail_on_exception in the cell output (stack traces). Would be good to re-run this notebook to get rid of these references.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 424 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAi2PV_4JyZgf30b5Ng:-OBCaf4I-aqYmMnajveq:b-h6106z) ([raw file](https://github.com/pixeltable/pixeltable/blob/21963aec6a108b5288a9cbe2931f4b99d6e00825/pixeltable/catalog/table.py#L424)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Oh... I thought we'd decided to allow it, but to prefer `pxt` types in our documentation. We should discuss again, I guess.
</blockquote></details>

just to close this out, builtins are now prohibited in schema specification
___
*[`tests/test_exprs.py` line 244 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/351#-OAid9eP4bsYupaZEisx:-OBD0S0A2JmOIpgtLbp0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/fa8c653a56ac8a3d3d08b95d33b8d1c3300d2b59/tests/test_exprs.py#L244)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

You mean because null_args_fn has one non-opt parameter? True, but the lambda tests one more scenario, which is still useful to validate (the handling of parameter lists with no optionals vs those with some optionals might diverge in the future).
</blockquote></details>

Done.

**Pull request merged**
