### PR TITLE
LRU eviction in FileCache

### PR DESCRIPTION
**Pull request by aaron-siegel**
- Enables LRU eviction in FileCache
- Switches config file format to `toml`
- Auto-generates `config.toml` if none exists
- Generates warnings in FileCache if content needs to be re-downloaded

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/276)

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/276)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/env.py` line 221 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xCmLz-Fyd0BdYMOfy:-O6xCmLz-Fyd0BdYMOfz:b-jwzgbj) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L221)):*
> ```Python
>         # Read in the config
>         self._config = Config.from_file(self._config_file)
>         self._cache_size_mb = self._config.get_int_value('cache_size_mb')
> ```

Should we allow more flexible specification, such as '20g', etc., and then just call this cache_size?
___
*[`pixeltable/env.py` line 547 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDLM8An4rqZkIlev_:-O6xDLM8An4rqZkIleva:btlk8yh) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L547)):*
> ```Python
> 
> 
> class Config:
> ```

Class comment mising
___
*[`pixeltable/env.py` line 553 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDua9D5igQ7ZPGcw7:-O6xDua9D5igQ7ZPGcw8:bdz5n11) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L553)):*
> ```Python
> 
>     @classmethod
>     def from_file(cls, path: Path) -> Config:
> ```

Function comment missing.

I feel like I need to read the entire code in order to understand what it's doing.
___
*[`pixeltable/env.py` line 560 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDk_I32YiDnto4TaN:-O6xDk_I32YiDnto4TaO:b-jr0uxg) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L560)):*
> ```Python
>                 except toml.TomlDecodeError as exc:
>                     raise excs.Error(f'Could not read config file: {str(path)}') from exc
>         else:
> ```

What is path expected to be in this branch?

Why not simply have a create_default_config((path) for this part?
___
*[`pixeltable/utils/filecache.py` line 166 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xH-eg5V7XSfWseTM0:-O6xH-eg5V7XSfWseTM1:b-u50yqj) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/utils/filecache.py#L166)):*
> ```Python
>         key = self._url_hash(url)
>         assert key not in self.cache
>         if not self.has_warned_about_eviction and key in self.keys_evicted_this_session:
> ```

In other words, you'll see exactly one such warning and then things stay silent. I think this is very easy to ignore, and also very easy not to realize that you're possibly downloading every single file you work with, every time you access it.

I think the user should see the warning for every top-level operation that runs into this problem. We should probably also show the cache config and cache stats, which can be used to figure out how much to increase the cache. If we just say 'a media file was retrieved multiple times...', that doesn't give you any indication of the magnitude of the problem or what a better cache size would look like.
___
*[`pixeltable/utils/filecache.py` line 198 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xIxb03cWQzw-Mjbfs:-O6xIxb18tTR8FOUrzI4:bwvkwas) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/utils/filecache.py#L198)):*
> ```Python
>                 self.keys_evicted_this_session.add(lru_entry.key)
>             os.remove(str(lru_entry.path))
>             _logger.debug(f'evicted entry for cell {lru_entry.key} from file cache')
> ```

might as well also log size
___
*[`tests/test_file_cache.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xK2_bDz6lOjkDpObx:-O6xK2_bDz6lOjkDpOby:b-o3q1mu) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L35)):*
> ```Python
> 
>         for index, (file, url) in enumerate(zip(image_files, image_urls)):
>             if index % 5 == 2:
> ```

why %5 == 2?
___
*[`tests/test_file_cache.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xKQkkBQDUDn5mTrJ2:-O6xKQkkBQDUDn5mTrJ3:beoeis9) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L44)):*
> ```Python
>             lru_tracker[index] = (url, file_info.st_size)
>             expected_cache_size += file_info.st_size
>             while expected_cache_size > test_capacity:
> ```

You're basically reimplementing the logic in FileCache here, which I think is problematic to do for a test.

I think a more direct test of the externally observable behavior is:
- access a sequence of n files that exceed the cache capacity
- then access them again, but in reverse order; the first k that fit within the capacity should come from the cache
___
*[`tests/test_file_cache.py` line 60 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xLfOB9sIpYiCQVjwT:-O6xLfOB9sIpYiCQVjwU:bfn241i) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L60)):*
> ```Python
> 
>         # The file cache uses last modified time to track recency. If we order the directory contents by last
>         # modified time, we should get an exact match vs. the LRU tracker.
> ```

This is again referencing implementation details of FileCache.

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/276)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 221 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xCmLz-Fyd0BdYMOfy:-O6yKj3L4v_6bxTjOjw3:b-pd7arg) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L221)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Should we allow more flexible specification, such as '20g', etc., and then just call this cache_size?
</blockquote></details>

I thought about this, and I looked around for a library that provides parsing of sizes like `20g`, and couldn't find any good options. Do you know of any? I'm a little hesitant to just roll our own size parser.
___
*[`pixeltable/env.py` line 547 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDLM8An4rqZkIlev_:-O6yM8XT7KBdC1LZB4RE:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L547)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Class comment mising
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 553 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDua9D5igQ7ZPGcw7:-O6yM9580K9Bqy21_iri:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L553)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Function comment missing.

I feel like I need to read the entire code in order to understand what it's doing.
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 560 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xDk_I32YiDnto4TaN:-O6yMScs5RFB6ArmzF3E:b6b69sj) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/env.py#L560)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What is path expected to be in this branch?

Why not simply have a create_default_config((path) for this part?
</blockquote></details>

I don't understand this comment
___
*[`pixeltable/utils/filecache.py` line 166 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xH-eg5V7XSfWseTM0:-O6yMWjEE4E98IOsu6JM:b4maten) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/utils/filecache.py#L166)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

In other words, you'll see exactly one such warning and then things stay silent. I think this is very easy to ignore, and also very easy not to realize that you're possibly downloading every single file you work with, every time you access it.

I think the user should see the warning for every top-level operation that runs into this problem. We should probably also show the cache config and cache stats, which can be used to figure out how much to increase the cache. If we just say 'a media file was retrieved multiple times...', that doesn't give you any indication of the magnitude of the problem or what a better cache size would look like.
</blockquote></details>

Ok let's talk about this at standup. I agree with you, but this involves the cache being aware of when a new "top-level operation" begins, which is a nontrivial change.
___
*[`pixeltable/utils/filecache.py` line 198 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xIxb03cWQzw-Mjbfs:-O6yN5u6BO96jFerTvpL:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/pixeltable/utils/filecache.py#L198)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

might as well also log size
</blockquote></details>

Done.
___
*[`tests/test_file_cache.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xK2_bDz6lOjkDpObx:-O6yN7ebA4FwvoOLr6BJ:bjbjhe0) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L35)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

why %5 == 2?
</blockquote></details>

Just an arbitrarily chosen pattern of occasional evictions.
___
*[`tests/test_file_cache.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xKQkkBQDUDn5mTrJ2:-O6yNEKLDttw9yJSgd4P:b-qys0ja) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L44)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

You're basically reimplementing the logic in FileCache here, which I think is problematic to do for a test.

I think a more direct test of the externally observable behavior is:
- access a sequence of n files that exceed the cache capacity
- then access them again, but in reverse order; the first k that fit within the capacity should come from the cache
</blockquote></details>

I suppose I could implement the test you are describing in addition to this one. But I don't see what it adds; I think it's implied by this test (i.e., is guaranteed to pass if this one does) and provides somewhat weaker coverage, since this test ensures that the cache continues to behave as expected over a span of a large number of insertion/refresh/eviction events. Note that the sequence of n files would have to include repetition in order to adequately test functionality (we specifically want to ensure that if a file already in the cache is accessed again, it is bumped to the front of the cache).

I don't agree this test is "reimplementing the logic in FileCache". It's separately implementing the logic of an LRU cache, which is a specific, well-defined pattern that is independent of FileCache. The test simply asserts that "FileCache behaves the way an LRU cache is expected to behave." Even if it were referencing something specific to the FileCache implementation, I don't see anything a priori wrong with that.
___
*[`tests/test_file_cache.py` line 60 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O6xLfOB9sIpYiCQVjwT:-O6yNREU6g2kKduZMBDF:b6fh4z) ([raw file](https://github.com/pixeltable/pixeltable/blob/b67d8cb0f8cc14a6407d4bc2569c0288fc8eb2f8/tests/test_file_cache.py#L60)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This is again referencing implementation details of FileCache.
</blockquote></details>

In this case I agree it references an implementation detail of FileCache. But I don't see anything wrong with this. I'd rather have this additional sanity check than not have it.

**Review by mkornacker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/276)* status: 0 of 17 files reviewed, 14 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/env.py` line 265 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7uaHkdABLH5_QyHcpg:-O7uaHkdABLH5_QyHcph:b-ia7r6h) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/env.py#L265)):*
> ```Python
>         # Read in the config
>         self._config = Config.from_file(self._config_file)
>         self._cache_size_gb = self._config.get_float_value('cache_size_gb')
> ```

Let's be more specific and call this file_cache_size_gb (or feel free to think of a better name). I anticipate adding other caches in the near future (eg, model_cache_size_gb, ...).
___
*[`pixeltable/catalog/table.py` line 37 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7uc8Ap5qFNY5ZIoiNg:-O7uc8Ap5qFNY5ZIoiNh:bc7ytlt) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/catalog/table.py#L37)):*
> ```Python
> 
> class Table(SchemaObject):
>     """Base class for table objects (base tables, views, snapshots)."""
> ```

Add here that every user-invoked operation that runs an ExecNode tree (directly or indirectly) needs to call FileCache.emit_eviction_warnings(), that's part of the abstraction now.
___
*[`pixeltable/utils/filecache.py` line 68 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7ukc9V8_epij3rRvZz:-O7ukc9V8_epij3rRv_-:bb1lo5) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L68)):*
> ```Python
>     num_evictions: int
>     keys_retrieved_this_session: set[str]  # keys retrieved (downloaded or accessed) this session
>     keys_evicted_this_session: set[str]  # keys that were evicted after having been retrieved this session
> ```

keys_evicted_after_retrieval?

Also, _this_session is redundant, all access stats are per-session.
___
*[`pixeltable/utils/filecache.py` line 77 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7udKfq1KloZh2kOuu9:-O7udKfq1KloZh2kOuuA:blcj11j) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L77)):*
> ```Python
>     # - It is subsequently retrieved a second time ("download after a previous retrieval")
>     # The contents of this set will be used to generate a more informative warning.
>     keys_multiply_downloaded: set[str]
> ```

Maybe something like evicted_working_set_keys is more to the point (they don't need to be downloaded multiple times in this session in order to qualify for that).
___
*[`pixeltable/utils/filecache.py` line 156 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7ueG6fDaTuSqODMLfU:-O7ueG6fDaTuSqODMLfV:b-5ll44o) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L156)):*
> ```Python
>                 f'Consider increasing the cache size to at least {round(suggested_cache_size / (1 << 30), 1)} GiB '
>                 f'(it is currently {round(self.capacity_bytes / (1 << 30), 1)} GiB).\n'
>                 f'You can do this by setting the value of `cache_size_gb` in: {str(Env.get()._config_file)}',
> ```

Doesn't have to be now, but I still think a pxt.set_config('file_cache_size_gb', 64, session=False) that would set it and also update the config file would be really handy. Now you have to go to an editor and reset your notebook.

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/276)* status: 0 of 17 files reviewed, 14 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 37 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7uc8Ap5qFNY5ZIoiNg:-O84tjzB9O_4OD2slVcy:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/catalog/table.py#L37)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Add here that every user-invoked operation that runs an ExecNode tree (directly or indirectly) needs to call FileCache.emit_eviction_warnings(), that's part of the abstraction now.
</blockquote></details>

Done.
___
*[`pixeltable/utils/filecache.py` line 68 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7ukc9V8_epij3rRvZz:-O84tsDg70NOgDZr6hKr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L68)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

keys_evicted_after_retrieval?

Also, _this_session is redundant, all access stats are per-session.
</blockquote></details>

Done.
___
*[`pixeltable/utils/filecache.py` line 77 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7udKfq1KloZh2kOuu9:-O84uIYq1uzyK2QE087g:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L77)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Maybe something like evicted_working_set_keys is more to the point (they don't need to be downloaded multiple times in this session in order to qualify for that).
</blockquote></details>

Done.
___
*[`pixeltable/utils/filecache.py` line 156 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/276#-O7ueG6fDaTuSqODMLfU:-O84uVg-8JHOdWxdeZSP:bpyz0u0) ([raw file](https://github.com/pixeltable/pixeltable/blob/fe5c1a710e1b9c351866c176f11ae3f800260e3e/pixeltable/utils/filecache.py#L156)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Doesn't have to be now, but I still think a pxt.set_config('file_cache_size_gb', 64, session=False) that would set it and also update the config file would be really handy. Now you have to go to an editor and reset your notebook.
</blockquote></details>

I created a ticket for this (PXT-299).

**Pull request merged**
