### PR TITLE
Initial support for converting FunctionCalls to SQL

### PR DESCRIPTION
**Pull request by mkornacker**
- this only works for scalar functions at the moment, not AggregateFunctions
- new class SqlElementCache: this will enable componsition of Select statements via a With clause, which is needed for creating Select statements for DataFrames with aggregate function calls

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 15 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 19 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Iq2ic1bmjjgZNN3yy:-O6Iq2ic1bmjjgZNN3yz:b862r31) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L19)):*
> ```Python
> 
> def _get_combined_ordering(
>         o1: list[tuple[exprs.Expr, bool]], o2: list[tuple[exprs.Expr, bool]]
> ```

Also remove `List` and `Tuple` as imports, if you're lowercasing them throughout a file
___
*[`pixeltable/plan.py` line 84 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RfRAe-Uyd5dhTG8Gr:-O6RfRAe-Uyd5dhTG8Gs:bg43m6w) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L84)):*
> ```Python
>         self.order_by_clause = [(e.resolve_computed_cols(), asc) for e, asc in order_by_clause]
> 
>         # not executable
> ```

is this comment still relevant?
___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6Rg2ku6Iv3sGsGTCah:bita6f3) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
> ```Python
>         if where_clause is not None:
>             where_clause_conjuncts, self.filter = where_clause.split_conjuncts(
>                 lambda e: self.sql_elements[e] is not None)
> ```

The expression `sql_elements[e] is not None` gets used a lot; I think it'd be clearer to capture it with a method, say, `sql_elements.has_sql(e)`. Bonus is that we could (I think?) get rid of the lambda (here and elsewhere), as in
```python
where_clause.split_conjuncts(self.sql_elements.has_sql)
```
___
*[`pixeltable/plan.py` line 209 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Iqc0I5L0PMgnV85QV:-O6Iqc0I5L0PMgnV85QW:b-95nj4x) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L209)):*
> ```Python
>             cls, tbl: catalog.TableVersionPath, where_clause: Optional[exprs.Expr] = None
>     ) -> sql.Select:
>         stmt = sql.select(sql.func.count('*'))
> ```

why do we need a `'*'` here? feels like a contrived attempt to mimic SQL in python. the parameterless `count()` is more natural to me
___
*[`pixeltable/exprs/expr.py` line 373 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rh4EtE2NTJPTS1N_d:-O6Rh4EtE2NTJPTS1N_e:btlyanu) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/expr.py#L373)):*
> ```Python
> 
>     @abc.abstractmethod
>     def sql_expr(self, sql_elements: 'pixeltable.exprs.SqlElementCache') -> Optional[sql.ColumnElement]:
> ```

This will give a type error if `pixeltable` is not imported. One solution would be to put this at the top of the file:
```python
if TYPE_CHECKING:
    from pixeltable import exprs
```
Then you can make this `sql_elements: 'exprs.SqlElementCache'`.
___
*[`pixeltable/exprs/row_builder.py` line 236 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RkC2725p68IgsYQ4j:-O6RkC2725p68IgsYQ4k:bwtrtyu) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L236)):*
> ```Python
>         if remove_duplicates:
>             seen: set[int] = set()  # seen Expr.ids
>             deduped = [e for e in expr_list if e.id not in seen and not seen.add(e.id)]
> ```

btw a standard way of doing this is
```
deduped = list({a: None for a in expr_list}.keys())
```
which will efficiently dedup the list in an order preserving way.

kinda sad that the Python API doesn't include a `list.unique()` method or some such.
___
*[`pixeltable/exprs/row_builder.py` line 237 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rjh_h2t0aZeLxcUab:-O6Rjh_h2t0aZeLxcUac:bjmaaxe) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L237)):*
> ```Python
>             seen: set[int] = set()  # seen Expr.ids
>             deduped = [e for e in expr_list if e.id not in seen and not seen.add(e.id)]
>             expr_list[:] = deduped
> ```

we're modifying the parameter in place? i think this should be called out in the function comment for clarity
___
*[`pixeltable/exprs/row_builder.py` line 239 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RjORJ2c7bs4gCwYeF:-O6RjORJ2c7bs4gCwYeG:btwbyst) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L239)):*
> ```Python
>             expr_list[:] = deduped
> 
>     def _set_slot_idxs_aux(self, e: Expr) -> None:
> ```

use double underscore: this is definitely a private method

i generally prefer `__set_slot_idxs_r` in this situation (`aux` is kinda weird) but don't feel strongly about it
___
*[`pixeltable/exprs/sql_element_cache.py` line 8 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6IrlXc2keV1jA1Jxg1:-O6IrlXc2keV1jA1Jxg2:bectscl) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/sql_element_cache.py#L8)):*
> ```Python
> 
> 
> class SqlElementCache:
> ```

The name `SqlElementCache` seems slightly misleading to me, since it's driving the actual evaluation, and part of its purpose is to capture separate evaluation contexts (whereas "cache" suggests we're temporarily storing some invariant for efficiency).

Maybe `SqlContext`?
___
*[`pixeltable/exprs/sql_element_cache.py` line 11 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RulfGESfF67Lc768o:-O6RulfGESfF67Lc768p:b-6zeh03) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/sql_element_cache.py#L11)):*
> ```Python
>     """Cache of sql.ColumnElements for exprs"""
> 
>     cache: dict[int, sql.ColumnElement]  # key: Expr.id
> ```

shouldn't this be a `dict[int, Optional[sql.ColumnElement]]` ?
___
*[`pixeltable/func/function.py` line 91 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Is07QBA8sHCFchm46:-O6Is07QBA8sHCFchm47:b-yanj7k) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/func/function.py#L91)):*
> ```Python
>         pass
> 
>     def _to_sql(self, *args: Any, **kwargs: Any) -> Optional['sqlalchemy.ColumnElement']:
> ```

This should probably just be a member variable rather than a method `def`. Defining a method via `def` and then later overriding it with an assignment is pretty confusing.

That is:

```
__sql_conversion_fn: Callable[..., Optional[sql.ColumnElement]] = None
```
and then:
```
def to_sql(...):
    self.__sql_conversion_fn = fn
```

See how `_conditional_return_type` is implemented, for example.
___
*[`pixeltable/func/function.py` line 100 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6IsoE59rffj_NA2yJG:-O6IsoE59rffj_NA2yJH:b723v93) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/func/function.py#L100)):*
> ```Python
> 
>     def to_sql(
>             self, fn: Callable[..., Optional['sqlalchemy.ColumnElement']]
> ```

The quoted type shouldn't be necessary here; just put `import sqlalchemy as sql` at top of file and use a proper type reference.
___
*[`pixeltable/functions/timestamp.py` line 33 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6ItwRe2dzu0tQmpzbv:-O6ItwRe2dzu0tQmpzbw:b-g9uul3) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L33)):*
> ```Python
> 
> 
> @year.to_sql
> ```

Every function that has a `to_sql` should have a test that executes it two ways: first in an expression that will be converted to SQL, then in an expression that can only be evaluated in Python.

(in this case, for example, one might enhance `test_all` so that in addition to calling `pxt_fn(t.dt, ...)`, we also call something like `pxt_fn(t.dt.apply(lambda x: x))`.)
___
*[`pixeltable/functions/timestamp.py` line 35 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6It1OiCSc3TdYtn3tC:-O6It1OiCSc3TdYtn3tD:bx3kmu9) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L35)):*
> ```Python
> @year.to_sql
> def _(self: sql.ColumnElement) -> sql.ColumnElement:
>     import sqlalchemy as sql
> ```

spurious import (here and elsewhere) - it's already imported at top of file
___
*[`pixeltable/functions/timestamp.py` line 50 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6ItVipD9iTOPa1mBnP:-O6ItVipD9iTOPa1mBnQ:b-jwotfy) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L50)):*
> ```Python
> 
> @month.to_sql
> def _(self: 'sqlalchemy.ColumnElement') -> 'sqlalchemy.ColumnElement':
> ```

unnecessary quoted type (here and elsewhere)

this will actually give a type error as printed, since `sqlalchemy` was imported as `sql`

(in fact, i'd expect it to generate an inline warning in pycharm, unless you've disabled them)

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 14 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 19 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Iq2ic1bmjjgZNN3yy:-O6SLJRO8xC8V13BPQVR:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L19)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Also remove `List` and `Tuple` as imports, if you're lowercasing them throughout a file
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 84 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RfRAe-Uyd5dhTG8Gr:-O6SLdTN0MNaIYbntdTo:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L84)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

is this comment still relevant?
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6SN2cp6Y7cEB924tYw:b1kirrj) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The expression `sql_elements[e] is not None` gets used a lot; I think it'd be clearer to capture it with a method, say, `sql_elements.has_sql(e)`. Bonus is that we could (I think?) get rid of the lambda (here and elsewhere), as in
```python
where_clause.split_conjuncts(self.sql_elements.has_sql)
```
</blockquote></details>

replaced with contains()
___
*[`pixeltable/plan.py` line 209 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Iqc0I5L0PMgnV85QV:-O6SNknw9NBMgfUbHddj:b-9dqgpn) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L209)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

why do we need a `'*'` here? feels like a contrived attempt to mimic SQL in python. the parameterless `count()` is more natural to me
</blockquote></details>

not needed, removed
___
*[`pixeltable/exprs/expr.py` line 373 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rh4EtE2NTJPTS1N_d:-O6SOXdS7g20Yp8G2KTr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/expr.py#L373)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This will give a type error if `pixeltable` is not imported. One solution would be to put this at the top of the file:
```python
if TYPE_CHECKING:
    from pixeltable import exprs
```
Then you can make this `sql_elements: 'exprs.SqlElementCache'`.
</blockquote></details>

Done.
___
*[`pixeltable/exprs/row_builder.py` line 236 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RkC2725p68IgsYQ4j:-O6SUsijASe-E4uStBvd:b-wi1ni4) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L236)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

btw a standard way of doing this is
```
deduped = list({a: None for a in expr_list}.keys())
```
which will efficiently dedup the list in an order preserving way.

kinda sad that the Python API doesn't include a `list.unique()` method or some such.
</blockquote></details>

We already have ExprSet...
___
*[`pixeltable/exprs/row_builder.py` line 237 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rjh_h2t0aZeLxcUab:-O6SPkEC2s87MHK41zSK:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L237)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

we're modifying the parameter in place? i think this should be called out in the function comment for clarity
</blockquote></details>

Done.
___
*[`pixeltable/exprs/row_builder.py` line 239 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RjORJ2c7bs4gCwYeF:-O6SPuzg6myK2R6Yp4s0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/row_builder.py#L239)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

use double underscore: this is definitely a private method

i generally prefer `__set_slot_idxs_r` in this situation (`aux` is kinda weird) but don't feel strongly about it
</blockquote></details>

Done.
___
*[`pixeltable/exprs/sql_element_cache.py` line 8 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6IrlXc2keV1jA1Jxg1:-O6SQDOV0RuqMJV6PTSu:b5fzscn) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/sql_element_cache.py#L8)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The name `SqlElementCache` seems slightly misleading to me, since it's driving the actual evaluation, and part of its purpose is to capture separate evaluation contexts (whereas "cache" suggests we're temporarily storing some invariant for efficiency).

Maybe `SqlContext`?
</blockquote></details>

I was thinking about that, but SqlContext seems a bit grandiose and vague. How about we defer this for now and see how it evolves?
___
*[`pixeltable/exprs/sql_element_cache.py` line 11 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6RulfGESfF67Lc768o:-O6SQ1tcBsPM8UVa5jJp:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/sql_element_cache.py#L11)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

shouldn't this be a `dict[int, Optional[sql.ColumnElement]]` ?
</blockquote></details>

Done.
___
*[`pixeltable/func/function.py` line 91 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Is07QBA8sHCFchm46:-O6SSaIY6gm3U1blz2ii:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/func/function.py#L91)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should probably just be a member variable rather than a method `def`. Defining a method via `def` and then later overriding it with an assignment is pretty confusing.

That is:

```
__sql_conversion_fn: Callable[..., Optional[sql.ColumnElement]] = None
```
and then:
```
def to_sql(...):
    self.__sql_conversion_fn = fn
```

See how `_conditional_return_type` is implemented, for example.
</blockquote></details>

Done.
___
*[`pixeltable/func/function.py` line 100 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6IsoE59rffj_NA2yJG:-O6SROeI7QZOOpzDirsG:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/func/function.py#L100)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The quoted type shouldn't be necessary here; just put `import sqlalchemy as sql` at top of file and use a proper type reference.
</blockquote></details>

Done.
___
*[`pixeltable/functions/timestamp.py` line 35 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6It1OiCSc3TdYtn3tC:-O6SSqJcCXZvUGW6Ejw7:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L35)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

spurious import (here and elsewhere) - it's already imported at top of file
</blockquote></details>

Done.
___
*[`pixeltable/functions/timestamp.py` line 50 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6ItVipD9iTOPa1mBnP:-O6STAs408ZGVDqcBftJ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L50)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

unnecessary quoted type (here and elsewhere)

this will actually give a type error as printed, since `sqlalchemy` was imported as `sql`

(in fact, i'd expect it to generate an inline warning in pycharm, unless you've disabled them)
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6XyXi_DxilY2at_OtJ:b-d1r3fw) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

replaced with contains()
</blockquote></details>

`contains()` is a little misleading, because its normal interpretation is "is contained in the cache". But an Expr could be contained in the cache, but still return None, because it previously had its sql_expr() evaluated, with a result of None. `has_sql()` seems clearer to me (or really, anything that clearly says "this Expr returned a positive result when it was converted to sql."
___
*[`pixeltable/exec/sql_node.py` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Xzz0UCTGOGVmLxqCA:-O6Xzz0UCTGOGVmLxqCB:bt2o3d1) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/exec/sql_node.py#L38)):*
> ```Python
>         # unstored iter columns: we also need to retrieve whatever is needed to materialize the iter args
>         for iter_arg in row_builder.unstored_iter_args.values():
>             sql_subexprs = iter_arg.subexprs(filter=lambda e: sql_elements[e] is not None, traverse_matches=False)
> ```

Replace lambda with sql_elements.has_sql (or whatever we want to call it)
___
*[`pixeltable/exprs/sql_element_cache.py` line 8 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6IrlXc2keV1jA1Jxg1:-O6az7VBB8jD_DqhdLm7:b32wtd) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/exprs/sql_element_cache.py#L8)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I was thinking about that, but SqlContext seems a bit grandiose and vague. How about we defer this for now and see how it evolves?
</blockquote></details>

ok
___
*[`pixeltable/func/function.py` line 46 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6azvE_CgHhqRV8BqlI:-O6azTwUEfi9GvNqBS5p:b-ykpsm1) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/func/function.py#L46)):*
> ```Python
>         self.is_property = is_property
>         self._conditional_return_type = None
>         self._to_sql = self.__to_sql
> ```

Why isn't the default `None`? That seems more logical to me than this pattern. Yes it would involve an extra line of code when `_to_sql` gets called, but I think that'd be clearer to anyone reading the code.
___
*[`pixeltable/func/function.py` line 111 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6b-8X04JYQEYNtc3Mj:-O6b-8X04JYQEYNtc3Mk:bgn92bg) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/func/function.py#L111)):*
> ```Python
>         return fn
> 
>     def __to_sql(self, *args: Any, **kwargs: Any) -> Optional[sql.ColumnElement]:
> ```

See above comment - I think we should get rid of this and have the default `_to_sql` be simply `None`.

If you feel strongly about keeping it, better to call it `__default_to_sql` or some such, and then the type of `_to_sql` is non-Optional.

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 10 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6b7vT0CvUQj0gvAva2:b-rlsko0) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`contains()` is a little misleading, because its normal interpretation is "is contained in the cache". But an Expr could be contained in the cache, but still return None, because it previously had its sql_expr() evaluated, with a result of None. `has_sql()` seems clearer to me (or really, anything that clearly says "this Expr returned a positive result when it was converted to sql."
</blockquote></details>

This is going with the customary interpretation of 'None' meaning 'doesn't have it' (as in dict.get()). The cache simply remembers the absence of a ColumnElement by placing an entry in a physical dict, but that's really internal to SqlElementCache.

I added comments to SqlElementCache.
___
*[`pixeltable/exec/sql_node.py` line 38 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Xzz0UCTGOGVmLxqCA:-O6b9N-T6RyAZWoglzD6:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/exec/sql_node.py#L38)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Replace lambda with sql_elements.has_sql (or whatever we want to call it)
</blockquote></details>

Done.
___
*[`pixeltable/func/function.py` line 46 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6azvE_CgHhqRV8BqlI:-O6b9VXC7TsFC7EhaQlm:b-bw0n6c) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/func/function.py#L46)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why isn't the default `None`? That seems more logical to me than this pattern. Yes it would involve an extra line of code when `_to_sql` gets called, but I think that'd be clearer to anyone reading the code.
</blockquote></details>

I think that's more error-prone. I find this completely clear, but added a comment to __to_sql() to clarify that it's the default implementation.
___
*[`pixeltable/func/function.py` line 111 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6b-8X04JYQEYNtc3Mj:-O6bA_-W-jc-xKes91ok:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/8d9f0d070f8e8b9b93f1df5f0209c5af94639569/pixeltable/func/function.py#L111)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

See above comment - I think we should get rid of this and have the default `_to_sql` be simply `None`.

If you feel strongly about keeping it, better to call it `__default_to_sql` or some such, and then the type of `_to_sql` is non-Optional.
</blockquote></details>

Done.
___
*[`pixeltable/functions/timestamp.py` line 33 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6ItwRe2dzu0tQmpzbv:-O6bCqYz2E6HDBv04-7U:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/functions/timestamp.py#L33)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Every function that has a `to_sql` should have a test that executes it two ways: first in an expression that will be converted to SQL, then in an expression that can only be evaluated in Python.

(in this case, for example, one might enhance `test_all` so that in addition to calling `pxt_fn(t.dt, ...)`, we also call something like `pxt_fn(t.dt.apply(lambda x: x))`.)
</blockquote></details>

Done.

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6bNDBC64umJa6CIhpU:b-88he9v) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This is going with the customary interpretation of 'None' meaning 'doesn't have it' (as in dict.get()). The cache simply remembers the absence of a ColumnElement by placing an entry in a physical dict, but that's really internal to SqlElementCache.

I added comments to SqlElementCache.
</blockquote></details>

```
d = {'a': None}
```
Now `'a' in d` returns `True`, but `'b' in d` returns `False`. I'd argue `contains()` implies semantics that mirror `in`, not `get()`.

**Review by aaron-siegel — APPROVED** [review]

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/278)* status: 0 of 37 files reviewed, 3 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 89 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/278#-O6Rg2ku6Iv3sGsGTCag:-O6coglO2Nb2euofHGzF:b-nf90r4) ([raw file](https://github.com/pixeltable/pixeltable/blob/d11569132f93263b6afe2d26776f62add3c8d468/pixeltable/plan.py#L89)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

```
d = {'a': None}
```
Now `'a' in d` returns `True`, but `'b' in d` returns `False`. I'd argue `contains()` implies semantics that mirror `in`, not `get()`.
</blockquote></details>

I changed SqlElementCache.__getitem__ to SqlElementCache.get

**Pull request merged**
