### PR TITLE
PXT-274 - Use GPUs for sentence_transformers when available

### PR DESCRIPTION
**Pull request by anushas**
This commit changes the following sentence_transformers udf
- sentence_transformer
- sentence_transformer_list
- cross_encoder
- cross_encoder_list to use the GPU when available by specifying the torch.device.

Testing: make test ran clean on laptop (assume, it uses mps gpu). CI should run with cpu. Pending test in colab for cuda gpu. It is not yet clear how to verify/confirm it uses the device.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anushas)

___
*[`pixeltable/functions/huggingface.py` line 56 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBBaTxP9HRAVLRS0AOA:-OBBaTxP9HRAVLRS0AOB:b-x2g2wd) ([raw file](https://github.com/pixeltable/pixeltable/blob/6c3b461b47b4bd1f26c57be02805937681c888e5/pixeltable/functions/huggingface.py#L56)):*
> ```Python
> 
>     # specifying the device, moves the model to device (gpu:cuda/mps, cpu)
>     model = _lookup_model(model_id, SentenceTransformer, device=device)
> ```

The code in `_lookup_model` needs to change. This won't work as-is if `device='cpu'` is explicitly specified.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/functions/huggingface.py` line 409 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDDF7I1pc0CGrRJ2ye:-OBDDF7I1pc0CGrRJ2yf:b-k46cjd) ([raw file](https://github.com/pixeltable/pixeltable/blob/98935bc7a3185b95815fff50f14081a05d7ccb00/pixeltable/functions/huggingface.py#L409)):*
> ```Python
>     key = (model_id, create, device)  # For safety, include the `create` callable in the cache key
>     if key not in _model_cache:
>         if create.__name__ in {'SentenceTransformer', 'CrossEncoder'}:
> ```

Best not to hard-code these here. It'd be cleaner to add another parameter to _lookup_model. Something like:
```
pass_device_to_create: bool = False
```
then specify it as `True` in `sentence_transformer` and `cross_encoder`.
___
*[`pixeltable/functions/huggingface.py` line 415 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDEBm-5VO7jVVKKSoK:-OBDEBm0DLlZiSCx2F0x:b-k4f3g8) ([raw file](https://github.com/pixeltable/pixeltable/blob/98935bc7a3185b95815fff50f14081a05d7ccb00/pixeltable/functions/huggingface.py#L415)):*
> ```Python
>         if isinstance(model, nn.Module):
>             if device is not None:
>                 model.to(device)
> ```

also skip this `model.to` invocation if `pass_device_to_create=True` (it's unnecessary in that case)

**Comment by anushas** [comment]
@aaron-siegel - PTAL, did the requested changes. 
For some reason one of the CI test is failing - ubuntu, lint, --with dev. It is complaining about 
_Uexpected keyword argument 'device'_ 
but the line number is EOF. And file is different on each run. Not sure what that means.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @anushas)

___
*[`pixeltable/functions/huggingface.py` line 419 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDOLiyCemyjMMlKL0l:-OBDOLiyCemyjMMlKL0m:b-wastll) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ac663ad8e1625b4d2c92a6dd16731cea75230f3/pixeltable/functions/huggingface.py#L419)):*
> ```Python
>             model = create(model_id)
>         if isinstance(model, nn.Module):
>             if pass_device_to_create == False and device is not None:
> ```

Python style comment:
```python
not pass_device_to_create
```
is preferred to
```python
pass_device_to_create == False
```

**Review by anushas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/functions/huggingface.py` line 56 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBBaTxP9HRAVLRS0AOA:-OBDOZ8r94lqKhS5eP4d:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7e62816f4550df4c65f14312f50cf4c175fb2274/pixeltable/functions/huggingface.py#L56)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

The code in `_lookup_model` needs to change. This won't work as-is if `device='cpu'` is explicitly specified.
</blockquote></details>

Done.
___
*[`pixeltable/functions/huggingface.py` line 409 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDDF7I1pc0CGrRJ2ye:-OBDOZpGEfRiWptLwYy5:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/98935bc7a3185b95815fff50f14081a05d7ccb00/pixeltable/functions/huggingface.py#L409)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Best not to hard-code these here. It'd be cleaner to add another parameter to _lookup_model. Something like:
```
pass_device_to_create: bool = False
```
then specify it as `True` in `sentence_transformer` and `cross_encoder`.
</blockquote></details>

Done.
___
*[`pixeltable/functions/huggingface.py` line 415 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDEBm-5VO7jVVKKSoK:-OBDOb4U4E0wQ7c3CExo:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/98935bc7a3185b95815fff50f14081a05d7ccb00/pixeltable/functions/huggingface.py#L415)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

also skip this `model.to` invocation if `pass_device_to_create=True` (it's unnecessary in that case)
</blockquote></details>

Done.

**Review by anushas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/361)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/functions/huggingface.py` line 419 at r4](https://reviewable.io/reviews/pixeltable/pixeltable/361#-OBDOLiyCemyjMMlKL0l:-OBDTkCf-e9SMRRNbtuk:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/2ac663ad8e1625b4d2c92a6dd16731cea75230f3/pixeltable/functions/huggingface.py#L419)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Python style comment:
```python
not pass_device_to_create
```
is preferred to
```python
pass_device_to_create == False
```
</blockquote></details>

Done.

**Comment by anushas** [comment]
fixed the type check error by relaxing the definition of the create parameter to _lookup_model as Callable[..., T]. this passed make typecheck locally.

**Pull request merged**
