### PR TITLE
Enable create_table to accept a DataFrame in place of a schema

### PR DESCRIPTION
**Pull request by aaron-siegel**

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/globals.py` line 37 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4H2EMO08ceT1WSYn6x:-O4H2EMO08ceT1WSYn6y:bixgqnq) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/globals.py#L37)):*
> ```Python
>     Args:
>         path_str: Path to the table.
>         schema_or_df: Either a dictionary that maps column names to column types, or a `DataFrame`
> ```

Link to DataFrame doc page.
___
*[`pixeltable/globals.py` line 63 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N78PX5k2B7mvU2e2b:-O4N78PX5k2B7mvU2e2c:bjqrnos) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/globals.py#L63)):*
> ```Python
>     dir = Catalog.get().paths[path.parent]
> 
>     df: Optional[DataFrame] = None
> ```

Maybe an explicit check with an error message if schema_or_df isn't the right type?

I can see someone doing this: create_table('a', t.select(...).collect()). Maybe this would even warrant a special check and error message.
___
*[`pixeltable/catalog/insertable_table.py` line 54 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N7iGa7j99LTybKlEd:-O4N7iGa7j99LTybKlEe:b-v6gyqn) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/catalog/insertable_table.py#L54)):*
> ```Python
>             _, tbl_version = TableVersion.create(session, dir_id, name, columns, num_retained_versions, comment)
>             tbl = cls(dir_id, tbl_version)
>             if df is not None and df.count() > 0:
> ```

Don't do count() here, that could be pretty expensive and in effect double the runtime of this operation. What's the downside of __insert_df() when the query returns nothing?
___
*[`pixeltable/catalog/insertable_table.py` line 80 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N8SWtD1INuJ-289DZ:-O4N8SWtD1INuJ-289D_:bbcy2ve) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/catalog/insertable_table.py#L80)):*
> ```Python
>                 }
>                 insert_batch.append(insert_row)
>             self.__validate_input_rows(insert_batch)  # Just in case
> ```

This should be validated in create_table(), not here. That also allows you to create more meaningful error messages.
___
*[`pixeltable/catalog/insertable_table.py` line 81 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N8uGp4gTqzs3ExkrM:-O4N8uGp4gTqzs3ExkrN:bfoj7by) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/catalog/insertable_table.py#L81)):*
> ```Python
>                 insert_batch.append(insert_row)
>             self.__validate_input_rows(insert_batch)  # Just in case
>             self._tbl_version.insert(insert_batch, conn=conn)
> ```

This creates one new version per row batch. That would be problematic, because revert() would take you back to a state that never existed.

I think this needs to be special-cased, ie, TableVersion.insert_df() or something like that.

What TableVersion.insert_df() should really do is to create a different insert plan which has the plan for the df at the bottom, in lieu of the InMemoryDataNode.

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/globals.py` line 37 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4H2EMO08ceT1WSYn6x:-O5Eu-UU6ReY3iaHuwh9:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/globals.py#L37)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Link to DataFrame doc page.
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 63 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N78PX5k2B7mvU2e2b:-O5Ev1GZ1CXtb7SpSkm7:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/globals.py#L63)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Maybe an explicit check with an error message if schema_or_df isn't the right type?

I can see someone doing this: create_table('a', t.select(...).collect()). Maybe this would even warrant a special check and error message.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/insertable_table.py` line 54 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O4N7iGa7j99LTybKlEd:-O5Ev8G07pk0LMIV5bO2:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/3a8cf9bd800cc5dd0b7ac6cd9610c8cb2081260a/pixeltable/catalog/insertable_table.py#L54)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Don't do count() here, that could be pretty expensive and in effect double the runtime of this operation. What's the downside of __insert_df() when the query returns nothing?
</blockquote></details>

Fixed

**Review by mkornacker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)* status: 0 of 18 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/globals.py` line 71 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5Z__O46SIGTLEzR6YS:-O5Z__O52V9w_2cGv2Um:b-a4nrem) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/globals.py#L71)):*
> ```Python
>         df = schema_or_df
>         schema = df.schema
>     else:
> ```

Also check for DataFrameResultSet and give a more specific error message
___
*[`pixeltable/plan.py` line 248 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5Zbd7VBQy97NM7INux:-O5Zbd7VBQy97NM7INuy:b2oh5in) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/plan.py#L248)):*
> ```Python
>         plan = df._create_query_plan()  # ExecNode constructed by the DataFrame
> 
>         # Augment the plan with columns of the target table
> ```

misleading comment: you're not augmenting the plan, you're simply registering the output columns with the RowBuilder
___
*[`pixeltable/catalog/insertable_table.py` line 54 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5ZaHNV9F5jIUT3-rVT:-O5ZaHNV9F5jIUT3-rVU:b-njlu7a) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/catalog/insertable_table.py#L54)):*
> ```Python
>             _, tbl_version = TableVersion.create(session, dir_id, name, columns, num_retained_versions, comment)
>             tbl = cls(dir_id, tbl_version)
>             session.commit()  # TODO I'm not sure why this commit is necessary
> ```

What happens without it? We shouldn't commit here, because you'll end up with an empty table if the insert() fails.
___
*[`pixeltable/catalog/table_version.py` line 646 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5ZcDB7331BHi4BXv16:-O5ZcDB7331BHi4BXv17:b-62vzwz) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/catalog/table_version.py#L646)):*
> ```Python
>             fail_on_exception: bool = True
>     ) -> UpdateStatus:
>         """Insert rows into this table.
> ```

Update comment

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)* status: 0 of 18 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/globals.py` line 71 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5Z__O46SIGTLEzR6YS:-O5dPROG-V6jPJmb-Uef:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/globals.py#L71)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Also check for DataFrameResultSet and give a more specific error message
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 248 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5Zbd7VBQy97NM7INux:-O5dPcbi8aoVOb_pEw7M:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/plan.py#L248)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

misleading comment: you're not augmenting the plan, you're simply registering the output columns with the RowBuilder
</blockquote></details>

Fixed
___
*[`pixeltable/catalog/insertable_table.py` line 54 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5ZaHNV9F5jIUT3-rVT:-O5dNzEEAeNEGtikWWS-:bj57qcj) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/catalog/insertable_table.py#L54)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

What happens without it? We shouldn't commit here, because you'll end up with an empty table if the insert() fails.
</blockquote></details>

Yeah, I understand. Without the commit, you get a primary key error on the metadata table when the insert happens. We need to refactor so that metadata gets written just once.

The right solution is user-specified transactions, which we're already planning to do. Rather than try to brute-force a one-off fix, it seems better to fold it in to that solution, and live with the fact that we'll get an extraneous empty table on failure (which already happens in several other places anyway).

I'll update the code comment to give a clearer description of the problem

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/246)* status: 0 of 18 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table_version.py` line 646 at r6](https://reviewable.io/reviews/pixeltable/pixeltable/246#-O5ZcDB7331BHi4BXv16:-O5dQTu47QO-rve4pNUc:b-99cr9a) ([raw file](https://github.com/pixeltable/pixeltable/blob/c81723cac3eb2ee9629cd7cccc4dc85ac2e54b7a/pixeltable/catalog/table_version.py#L646)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Update comment
</blockquote></details>

Done. It was still technically correct, but I clarified it :)

**Pull request merged**
