### PR TITLE
Support for batch updates

### PR DESCRIPTION
**Pull request by mkornacker**
This includes support for the '_rowid' pseudo-column; ex.: update([{'col1': 1, '_rowid': (1,)}])

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/132)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/132)* status: 0 of 9 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 550 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_KRt0bLqz7LN400Z:-Nw0_KRt0bLqz7LN400_:b-6hfffd) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L550)):*
> ```Python
> 
>     def update(
>             self, value_spec: Union[list[dict[str, Any]], dict[str, Any]],
> ```

This no longer takes a list of dicts, right? Since that functionality moved to `update_batch`.
___
*[`pixeltable/catalog/table.py` line 558 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_OX3Au8fpc_rhxKE:-Nw0_OX3Au8fpc_rhxKF:bbxgkzp) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L558)):*
> ```Python
>             value_spec: one of
>             * a dictionary mapping column names to literal values or Pixeltable expressions.
>             * a list of dictionaries containing values for the updated columns plus values for the primary key columns.
> ```

Same comment as above
___
*[`pixeltable/catalog/table.py` line 597 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_iY-6AxpjyHhBe6f:-Nw0_iY-6AxpjyHhBe6g:b-tnfmo6) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L597)):*
> ```Python
>         return self.tbl_version_path.tbl_version.update(update_spec, where, cascade)
> 
>     def update_batch(self, rows: list[dict[str, Any]], cascade: bool = True
> ```

rows should be an `Iterable[dict[str, Any]]`

(Change it to an `Iterable`, then put `rows = list(rows)` as the first statement of your method, and you'll get a more general API with no additional modifications needed)
___
*[`pixeltable/catalog/table.py` line 598 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_bY60teb-zNri1GT:-Nw0_bY60teb-zNri1GU:b-6veipq) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L598)):*
> ```Python
> 
>     def update_batch(self, rows: list[dict[str, Any]], cascade: bool = True
>     ) -> UpdateStatus:
> ```

Unintended newline?
___
*[`pixeltable/catalog/table.py` line 616 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bmrJ-dxvcYDEegHU:-Nw0bmrJ-dxvcYDEegHV:b87neq0) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L616)):*
> ```Python
> 
>         row_updates: List[Dict[Column, exprs.Expr]] = []
>         pk_col_names = set(c.name for c in self.tbl_version_path.tbl_version.primary_key_columns())
> ```

This should probably just be a precomputed field of TableVersion
___
*[`pixeltable/catalog/table.py` line 626 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bRK95HGLl9TpbYeJ:-Nw0apVA7QHv6WpDXCrm:bumvoaa) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L626)):*
> ```Python
>         for row_spec in rows:
>             col_vals = self._validate_update_spec(row_spec, allow_pk=True, allow_exprs=False)
>             col_names = set(col.name for col in col_vals.keys())
> ```

This is somewhat inefficient; the following would be faster (avoids explicit set creation and skips the slow check if `has_rowid`):
```
if not has_rowid:
    if any(pk_col_name not in col_vals for pk_col_name in pk_col_names):
        # Now we compute `missing_cols` and throw an exception
```
Could actually make a meaningful performance difference on very large updates.
___
*[`pixeltable/catalog/table.py` line 630 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0c6qM1doS9CXBl9lD:-Nw0c6qM1doS9CXBl9lE:b-p9aysm) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L630)):*
> ```Python
>                 missing_cols = pk_col_names - col_names
>                 raise excs.Error(f'Primary key columns ({", ".join(missing_cols)}) missing in {row_spec}')
>             if has_rowid:
> ```

Consolidate with preceding comment and reorganize as

```
if has_rowid:
    # ...
else:
    # ...
```
for clarity
___
*[`pixeltable/catalog/table.py` line 635 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0aAbk6I-3UsbKE-74:-Nw0aAbk6I-3UsbKE-75:bzecurj) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L635)):*
> ```Python
>                 rowids.append(row_spec[self.ROWID_COLUMN_NAME])
>             row_updates.append(col_vals)
>         return self.tbl_version_path.tbl_version.batch_update(row_updates, rowids, cascade)
> ```

Wait, this was called `update_batch` in one place and `batch_update` in the other. Let's try to be consistent?

(I kind of like `batch_update` but mostly want to see consistency)
___
*[`pixeltable/catalog/table_version.py` line 662 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0dEqJA_3ExbcOeNh9:-Nw0dEqJA_3ExbcOeNhA:b-w53zt7) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table_version.py#L662)):*
> ```Python
>                 if use_rowids:
>                     # construct Where clause to match rowid
>                     num_rowid_cols = len(self.store_tbl.rowid_columns())
> ```

Can this actually be > 1?
___
*[`pixeltable/tests/test_table.py` line 671 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0dkpEBKi09B3sc_-b:-Nw0dkpEBKi09B3sc_-c:bt1ut6x) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/tests/test_table.py#L671)):*
> ```Python
>         _  = t2.show(n=0)
> 
>     def test_update_batch(self, test_tbl: pxt.Table) -> None:
> ```

It looks like there are a few missing test cases.
- first entry in batch contains `_rowid` but subsequent entry does not
- successful batch update using `_rowid` in table with no primary key

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/132)* status: 0 of 11 files reviewed, 10 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/table.py` line 550 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_KRt0bLqz7LN400Z:-Nw0ggnY4JfsyMe-rneV:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L550)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This no longer takes a list of dicts, right? Since that functionality moved to `update_batch`.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 558 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_OX3Au8fpc_rhxKE:-Nw0gstBAcE7oDHqQ3yV:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L558)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 597 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_iY-6AxpjyHhBe6f:-Nw0hAsq2EeVvUQwNYAo:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L597)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

rows should be an `Iterable[dict[str, Any]]`

(Change it to an `Iterable`, then put `rows = list(rows)` as the first statement of your method, and you'll get a more general API with no additional modifications needed)
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 598 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0_bY60teb-zNri1GT:-Nw0hBg5CyNChmtWU836:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L598)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Unintended newline?
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 616 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bmrJ-dxvcYDEegHU:-Nw0tWgODbruEAqJRPiP:b6qy1nl) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L616)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This should probably just be a precomputed field of TableVersion
</blockquote></details>

I don't want to add this is a precomputed field, because every precomputed field comes with the risk of it getting out of sync with the underlying data.  This is still just a single line, so not hugely burdensome.
___
*[`pixeltable/catalog/table.py` line 626 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bRK95HGLl9TpbYeJ:-Nw0uDy-0Msc-RQ54svu:b-a93zex) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L626)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is somewhat inefficient; the following would be faster (avoids explicit set creation and skips the slow check if `has_rowid`):
```
if not has_rowid:
    if any(pk_col_name not in col_vals for pk_col_name in pk_col_names):
        # Now we compute `missing_cols` and throw an exception
```
Could actually make a meaningful performance difference on very large updates.
</blockquote></details>

This doesn't work, because col_vals has Columns as its key
___
*[`pixeltable/catalog/table.py` line 630 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0c6qM1doS9CXBl9lD:-Nw0uEqL2JdZUffa0yWM:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L630)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Consolidate with preceding comment and reorganize as

```
if has_rowid:
    # ...
else:
    # ...
```
for clarity
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 635 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0aAbk6I-3UsbKE-74:-Nw0hVTD8XTIYuEI_W17:b8ztw5k) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L635)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Wait, this was called `update_batch` in one place and `batch_update` in the other. Let's try to be consistent?

(I kind of like `batch_update` but mostly want to see consistency)
</blockquote></details>

I don't see a pressing need for consistency here. No user will ever interact with TableVersion.
___
*[`pixeltable/catalog/table_version.py` line 662 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0dEqJA_3ExbcOeNh9:-Nw0uZkL6UQe6eqJBAfK:b2nhswy) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table_version.py#L662)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Can this actually be > 1?
</blockquote></details>

Yes
___
*[`pixeltable/tests/test_table.py` line 671 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0dkpEBKi09B3sc_-b:-Nw0wu_o02G-q6Y1DIcu:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/tests/test_table.py#L671)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It looks like there are a few missing test cases.
- first entry in batch contains `_rowid` but subsequent entry does not
- successful batch update using `_rowid` in table with no primary key
</blockquote></details>

Done.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/132)* status: 0 of 11 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 616 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bmrJ-dxvcYDEegHU:-Nw37VIdDDJDI1ToBI06:b-orumjy) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L616)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I don't want to add this is a precomputed field, because every precomputed field comes with the risk of it getting out of sync with the underlying data.  This is still just a single line, so not hugely burdensome.
</blockquote></details>

Good point
___
*[`pixeltable/catalog/table.py` line 626 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0bRK95HGLl9TpbYeJ:-Nw37sUL09QDxbgT11Fp:b-smz989) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L626)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

This doesn't work, because col_vals has Columns as its key
</blockquote></details>

Ah bummer. Might as well use issubset then, I guess
___
*[`pixeltable/catalog/table.py` line 635 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0aAbk6I-3UsbKE-74:-Nw38WBQ3owUNcuxPCWp:b-u5che9) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table.py#L635)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I don't see a pressing need for consistency here. No user will ever interact with TableVersion.
</blockquote></details>

Right, but we might as well strive for consistency in the codebase? It's not just about the public api. Is there some argument *against* being consistent here?

EDIT: I see you changed it to batch_update. Great.
___
*[`pixeltable/catalog/table_version.py` line 662 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/132#-Nw0dEqJA_3ExbcOeNh9:-Nw38mknCyoI8mmyEjyP:b-vvspmg) ([raw file](https://github.com/pixeltable/pixeltable/blob/7360a590469087670a2e86375154fa4a22b51fee/pixeltable/catalog/table_version.py#L662)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

I'd love to understand this better.

**Pull request merged**
