### PR TITLE
PXT-334 - Add columns property to the table handle

### PR DESCRIPTION
**Pull request by anushas**
This commit adds a columns property to the catalog.Table class. 
This is for user convenience to fetch the list of columns for a table.

Testing: 
new basic unit test added that verifies t.columns returns what we expect.
Also had to adjust other existing test code that was using t.columns() API.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/359)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/359)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @anushas)

___
*[`tests/test_table.py` line 118 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzxMgP7oSLCSr1IPmD:-OAzxMgP7oSLCSr1IPmE:b1jukot) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L118)):*
> ```Python
> 
>     def test_columns(self, reset_db) -> None:  # noqa: PLR6301
>         pxt.create_dir('dir1')
> ```

No need to create a dir here.
___
*[`tests/test_table.py` line 126 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzwcqy6gq5isyuBajZ:-OAzwcqy6gq5isyuBaj_:bnrjwwo) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L126)):*
> ```Python
>         }
>         t = pxt.create_table('test', schema)
>         colList = t.columns
> ```

Python style: use underscore-separated variable names: `col_list` instead of `colList`

although you could also just write:

```python
assert t.columns == ['c1', 'c2', 'c3', 'c4']
```
___
*[`tests/test_table.py` line 1151 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzyLOp-OKJpN0Cgnai:-OAzyLOp-OKJpN0Cgnaj:ble827z) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L1151)):*
> ```Python
> 		# RESOLVE: comparing t == t? should this be t'?
>         t = pxt.get_table('test')
>         assert len(t._tbl_version_path.columns()) == len(t.columns)
> ```

This is actually a bug in Pixeltable's `Table.__getattr__()` implementation! Let's discuss tomorrow, but `Table.__getattr__()` probably shouldn't be calling `TableVersionPath.__getattr__()`. Tests that rely on this behavior need to be fixed; at first glance I think your solution of directly calling `t._tbl_version_path.columns()` makes sense.
___
*[`tests/test_table.py` line 1253 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzzUSv0QUKRd7pixab:-OAzzUSv0QUKRd7pixac:byagx3n) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L1253)):*
> ```Python
>         for i in range(len(t.columns)):
>             if t.columns[i] is not None:
>                 assert t.columns[i] == t2.columns[i]
> ```

this changes the meaning of the test (i think we want to continue to reference the `value_expr`s, not just the column names)
___
*[`tests/utils.py` line 97 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzznuc4I-TWK4_xYPc:-OAzznuc4I-TWK4_xYPd:b-m8ckck) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/utils.py#L97)):*
> ```Python
> 	# from tests. It is done the handle returned by pxt.create_table() API.
> 	# Yet, we called t.columns() here. AFAICT, the columns() API is only available
> 	# for catalog.TableVersionPath and that API returns list[Column] (and not list
> ```

I think you're doing the right thing calling `t._tbl_version_path.columns()` directly. Previously `t.columns()` was falling through to `TableVersionPath`, inappropriately surfacing the internal `Column` class as part of the public `Table` API. I'll look again in the morning

**Review by anushas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/359)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @aaron-siegel)

___
*[`tests/test_table.py` line 118 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzxMgP7oSLCSr1IPmD:-OB2AZpI3wlp-B0UnQx-:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L118)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

No need to create a dir here.
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 126 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzwcqy6gq5isyuBajZ:-OB2AnRH1EW_Vofxy76s:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L126)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Python style: use underscore-separated variable names: `col_list` instead of `colList`

although you could also just write:

```python
assert t.columns == ['c1', 'c2', 'c3', 'c4']
```
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 1151 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzyLOp-OKJpN0Cgnai:-OB2AqYJ-gXvcqJtaB9I:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L1151)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is actually a bug in Pixeltable's `Table.__getattr__()` implementation! Let's discuss tomorrow, but `Table.__getattr__()` probably shouldn't be calling `TableVersionPath.__getattr__()`. Tests that rely on this behavior need to be fixed; at first glance I think your solution of directly calling `t._tbl_version_path.columns()` makes sense.
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 1253 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzzUSv0QUKRd7pixab:-OB2AvVy9yDnDCJjZqFX:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/test_table.py#L1253)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

this changes the meaning of the test (i think we want to continue to reference the `value_expr`s, not just the column names)
</blockquote></details>

Done.
___
*[`tests/utils.py` line 97 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OAzznuc4I-TWK4_xYPc:-OB2Axz82AxxtI0QPjyW:bs7wumx) ([raw file](https://github.com/pixeltable/pixeltable/blob/99376eb7bbf1b5e34e9446bc8ce2dcdc63419ff6/tests/utils.py#L97)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I think you're doing the right thing calling `t._tbl_version_path.columns()` directly. Previously `t.columns()` was falling through to `TableVersionPath`, inappropriately surfacing the internal `Column` class as part of the public `Table` API. I'll look again in the morning
</blockquote></details>

Done.

**Comment by anushas** [comment]
Latest refresh is for a minor test fix (probably a typo) in test_computed_cols

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/359)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anushas)

___
*[`tests/test_table.py` line 1152 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OB2jI_G6V89Br8gS30n:-OB2jI_G6V89Br8gS30o:b-o14dio) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc1ac379e42a7af63d90387ee8d59e7641b33554/tests/test_table.py#L1152)):*
> ```Python
>         for i in range(len(t._tbl_version_path.columns())):
>             if t._tbl_version_path.columns()[i].value_expr is not None:
>                 assert t._tbl_version_path.columns()[i].value_expr.equals(t2._tbl_version_path.columns()[i].value_expr)
> ```

One last comment: the test might be more readable if we assign t._tbl_version_path.columns() and t2._tbl_version_path.columns() to variables, since they're each accessed three or four times

**Review by anushas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/359)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

___
*[`tests/test_table.py` line 1152 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/359#-OB2jI_G6V89Br8gS30n:-OB3CcRdBkf1IHd9RHSC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc1ac379e42a7af63d90387ee8d59e7641b33554/tests/test_table.py#L1152)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

One last comment: the test might be more readable if we assign t._tbl_version_path.columns() and t2._tbl_version_path.columns() to variables, since they're each accessed three or four times
</blockquote></details>

Done.

**Pull request merged**
