### PR TITLE
More progress on type checking

### PR DESCRIPTION
**Pull request by aaron-siegel**
- Type-safe `plan.py`: `mypy pixeltable/*.py` now succeeds
- Add type stubs for various libraries as dependencies

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 74 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F84JA7khR9s69Uyug:-O5F84JB6yVSaNCheeGH:bxikopa) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L74)):*
> ```Python
>         if self.filter is not None:
>             self.all_exprs.append(self.filter)
>         self.sql_exprs: list[exprs.Expr] = list(exprs.Expr.list_subexprs(
> ```

Isn't this inferred?
___
*[`pixeltable/plan.py` line 87 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8CDRCm6y2JWRrCjx:-O5F8CDRCm6y2JWRrCjy:b-fmapru) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L87)):*
> ```Python
>     def _analyze_agg(self) -> None:
>         """Check semantic correctness of aggregation and fill in agg-specific fields of Analyzer"""
>         self.agg_fn_calls = [e for e in self.all_exprs if isinstance(e, exprs.FunctionCall) and _is_agg_fn_call(e)]
> ```

Why is that isinstance() needed? It's technically redundant.

consider explaining that in a comment
___
*[`pixeltable/plan.py` line 101 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8atk-gvIASjzdQaK:-O5F8atk-gvIASjzdQaL:brhumzt) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L101)):*
> ```Python
>         # check that filter doesn't contain aggregates
>         if self.filter is not None:
>             agg_fn_calls = [e for e in self.filter.subexprs(expr_class=exprs.FunctionCall, filter=lambda e: _is_agg_fn_call(e))]
> ```

Same here.
___
*[`pixeltable/plan.py` line 217 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8ePIBzrQKoaI5AuP:-O5F8ePIBzrQKoaI5AuQ:b9o3adm) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L217)):*
> ```Python
>         stored_img_col_info = [info for info in stored_col_info if info.col.col_type.is_image_type()]
>         input_col_info = [info for info in stored_col_info if not info.col.is_computed]
>         plan: exec.ExecNode = exec.InMemoryDataNode(tbl, rows, row_builder, tbl.next_rowid)
> ```

Why is that needed?
___
*[`pixeltable/plan.py` line 297 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F99y2576vhHIAn49a:-O5F99y2576vhHIAn49b:b-70aa19) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L297)):*
> ```Python
>             batch: list[dict[catalog.Column, exprs.Expr]], rowids: list[tuple[int, ...]],
>             cascade: bool
>     ) -> Tuple[exec.ExecNode, exec.RowUpdateNode, sql.BinaryExpression[bool], List[catalog.Column], List[catalog.Column]]:
> ```

Why can't this be a ColumnElement?
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F9Uvm-TtEB-kvScKO:-O5F9Uvm-TtEB-kvScKP:b3kre) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L533)):*
> ```Python
>             if not isinstance(e, exprs.ColumnRef):
>                 return False
>             e.col
> ```

?

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 74 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F84JA7khR9s69Uyug:-O5G_dUF5N9klyWGQwSt:b-vjcwt9) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L74)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Isn't this inferred?
</blockquote></details>

No, sadly, mypy complains that it needs a type hint.
___
*[`pixeltable/plan.py` line 87 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8CDRCm6y2JWRrCjx:-O5G_i3y0sKkByWPOP8E:bkguqb9) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L87)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why is that isinstance() needed? It's technically redundant.

consider explaining that in a comment
</blockquote></details>

It's not redundant b/c the type checker doesn't know that `_is_agg_fn_call(e) == True` implies `e` is a `FunctionCall` (and there's really no reason it should). I can add a comment, though that seems silly to me; it's fairly obvious why it's needed
___
*[`pixeltable/plan.py` line 101 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8atk-gvIASjzdQaK:-O5GaDWYDAb3z7ccNyYm:bbskl09) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L101)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Right. Same reason.
___
*[`pixeltable/plan.py` line 217 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F8ePIBzrQKoaI5AuP:-O5GaHKY-NEY3TvbdVXi:b-qgb4an) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L217)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why is that needed?
</blockquote></details>

Because `plan` later gets set to something that isn't an `InMemoryDataNode`
___
*[`pixeltable/plan.py` line 297 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F99y2576vhHIAn49a:-O5GaiQxBCHS1X5EJ0CU:b-szlge0) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L297)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Why can't this be a ColumnElement?
</blockquote></details>

It could, but best practice is for return values to indicate the most specific type (and correspondingly, parameters to indicate the most general acceptable type)

I don't feel super strongly about this one though
___
*[`pixeltable/plan.py` line 533 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F9Uvm-TtEB-kvScKO:-O5Gb87mApAsQCU_T4v-:b-g6z5kx) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L533)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

?
</blockquote></details>

lol. Don't know where that came from. Fixed

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 74 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F84JA7khR9s69Uyug:-O5JZ-W50jXYqPFWnL7E:b-rb8i9m) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L74)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

No, sadly, mypy complains that it needs a type hint.
</blockquote></details>

I was able to resolve this one using overloads for `list_subexprs`. Let me know what you think (it feels right to me)

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 297 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F99y2576vhHIAn49a:-O5K-S9L25k2cG9Bwnws:b-uu737x) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L297)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It could, but best practice is for return values to indicate the most specific type (and correspondingly, parameters to indicate the most general acceptable type)

I don't feel super strongly about this one though
</blockquote></details>

Let's stick with ColumnElement[bool] here, to keep it general.
___
*[`pixeltable/exprs/expr.py` line 253 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5K0MbbCEc9RpfbPzRg:-O5K0MbbCEc9RpfbPzRh:bh1cq35) ([raw file](https://github.com/pixeltable/pixeltable/blob/2f6ddfbe4fc3b8afecc81ae397dd5d12094d0038/pixeltable/exprs/expr.py#L253)):*
> ```Python
>     @overload
>     def subexprs(
>         self, /, filter: Optional[Callable[[Expr], bool]] = None, traverse_matches: bool = True
> ```

/ -> *

**Review by mkornacker — APPROVED** [review]

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/263)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 297 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5F99y2576vhHIAn49a:-O5Men4y1TOPwQrfhUrY:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/1ada7d5effb6cce3b3ff41fe40e1c0877d974362/pixeltable/plan.py#L297)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Let's stick with ColumnElement[bool] here, to keep it general.
</blockquote></details>

Done
___
*[`pixeltable/exprs/expr.py` line 253 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/263#-O5K0MbbCEc9RpfbPzRg:-O5MeslY-YbJsCDJwNx8:b-886gsx) ([raw file](https://github.com/pixeltable/pixeltable/blob/2f6ddfbe4fc3b8afecc81ae397dd5d12094d0038/pixeltable/exprs/expr.py#L253)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

/ -> *
</blockquote></details>

Fixed

**Pull request merged**
