### PR TITLE
Add Context-Aware Discord Bot with Semantic Search Capabilities

### PR DESCRIPTION
**Pull request by pierrebrunelle**
**Description:** Implements a Discord bot with semantic search and context-aware responses using Pixeltable for efficient data management.

**Key features:**
- Semantic message search with relevance scoring
- Context-aware chat responses using historical message data
- Structured message embedding and indexing
- Discord message formatting with customized embeds for:
   - Search results with relevance scores
   - Chat responses with contextual information
   - Error handling with user-friendly displays

See **README.md** for details.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/367)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/367)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @pierrebrunelle)

___
*[`examples/context-aware-discord-bot/bot.py` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBSwhBiAED6i2HvVNCr:-OBSwhBiAED6i2HvVNCs:blhl62e) ([raw file](https://github.com/pixeltable/pixeltable/blob/34968b16c590736767c1019420ed0d579a9c6315/examples/context-aware-discord-bot/bot.py#L1)):*
> ```Python
> import os
> ```

organize imports
___
*[`examples/context-aware-discord-bot/bot.py` line 25 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTkXf47bkvGx5cKscF:-OBTkXf47bkvGx5cKscG:b-7pfcz8) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L25)):*
> ```Python
>         intents.message_content = True
>         self.bot = commands.Bot(command_prefix="/", intents=intents)
>         
> ```

are you using vscode? assuming yes, can you ensure you have "trim trailing whitespace" set to true in settings?
___
*[`examples/context-aware-discord-bot/bot.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTknNfBQ-BEwe-Pnw8:-OBTknNfBQ-BEwe-Pnw9:b-7lijbs) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L35)):*
> ```Python
> 
>     @staticmethod
>     @pxt.expr_udf
> ```

let's make a note to use the new embeddings pattern once it's shipped :)
___
*[`examples/context-aware-discord-bot/bot.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTl-Nt4TWS4OuwC21-:-OBTl-Nt4TWS4OuwC210:b-85jv39) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L44)):*
> ```Python
>         try:            
>             pxt.drop_dir('discord_bot', force=True)
>             pxt.create_dir('discord_bot', ignore_errors=True)
> ```

`ignore_errors=True` shouldn't be necessary, since you just force-dropped the dir
___
*[`examples/context-aware-discord-bot/bot.py` line 102 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXdIHZ4LPpLT_foJ5a:-OBXdIHZ4LPpLT_foJ5b:b-tevh0m) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L102)):*
> ```Python
>                         sim=sim
>                     )
>                     .limit(5)
> ```

Does this mean we're feeding OpenAI just the (at most) 5 most relevant messages? Curious if you've experimented with different values here (it could certainly handle a lot more?)
___
*[`examples/context-aware-discord-bot/bot.py` line 127 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXbGQW0Go3q9Bm2pXm:-OBXbGQW0Go3q9Bm2pXn:bxjxyoc) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L127)):*
> ```Python
>                     {
>                         "role": "system",
>                         "content": f'''
> ```

This shouldn't need an f-specifier since it's a constant string (no embedded variables)

Also, it'd be clearer to break this string out into a constant somewhere (`PixeltableBot.SYSTEM_PROMPT` or some such)
___
*[`examples/context-aware-discord-bot/bot.py` line 269 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXc2ch7c8r-x4YKncn:-OBXc2ch7c8r-x4YKnco:b-u5sv3d) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L269)):*
> ```Python
> def main():
>     load_dotenv()
>     token = os.getenv('DISCORD_TOKEN', 'OPENAI_API_KEY')
> ```

i don't think this is what you want; it will set `token` to the string `'OPENAI_API_KEY'` if `DISCORD_TOKEN` is not found in the environment. Just do

```python
token = os.getenv('DISCORD_TOKEN')
```

if `OPENAI_API_KEY` is missing, Pixeltable will complain later.
___
*[`examples/context-aware-discord-bot/message_formatter.py` line 14 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXc_NrCg8-ffx_uanN:-OBXc_NrCg8-ffx_uanO:bpyrrlg) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/message_formatter.py#L14)):*
> ```Python
>     
>     @staticmethod
>     def create_search_embed(results: List[Dict], query: str) -> discord.Embed:
> ```

use lowercase `list`, `dict` (the upper case variants are only necessary for Python 3.8 compatibility)

**Review by pierrebrunelle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/367)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @aaron-siegel)

___
*[`examples/context-aware-discord-bot/bot.py` line 1 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBSwhBiAED6i2HvVNCr:-OBd6LSu72NVImRdYoSp:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/34968b16c590736767c1019420ed0d579a9c6315/examples/context-aware-discord-bot/bot.py#L1)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

organize imports
</blockquote></details>

Done.
___
*[`examples/context-aware-discord-bot/bot.py` line 25 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTkXf47bkvGx5cKscF:-OBd79y26lzr96zo-Cnu:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L25)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

are you using vscode? assuming yes, can you ensure you have "trim trailing whitespace" set to true in settings?
</blockquote></details>

Done.
___
*[`examples/context-aware-discord-bot/bot.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTknNfBQ-BEwe-Pnw8:-OBd7EQT3qDvAELZwOsD:b5isiy6) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L35)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

let's make a note to use the new embeddings pattern once it's shipped :)
</blockquote></details>

Yes will go replace everywhere.
___
*[`examples/context-aware-discord-bot/bot.py` line 44 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBTl-Nt4TWS4OuwC21-:-OBd7JLm4XBF7MkEI8Uw:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L44)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`ignore_errors=True` shouldn't be necessary, since you just force-dropped the dir
</blockquote></details>

Done.
___
*[`examples/context-aware-discord-bot/bot.py` line 102 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXdIHZ4LPpLT_foJ5a:-OBd7KST22HIWfYHP5uR:b-st0e1n) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L102)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Does this mean we're feeding OpenAI just the (at most) 5 most relevant messages? Curious if you've experimented with different values here (it could certainly handle a lot more?)
</blockquote></details>

yes. let's move it to 10. Overall it's just an example. My prod example is feeding 20 + additional join.
___
*[`examples/context-aware-discord-bot/bot.py` line 127 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXbGQW0Go3q9Bm2pXm:-OBd7ZhZ4mA1Dp_1otOh:b-pxr75u) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L127)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This shouldn't need an f-specifier since it's a constant string (no embedded variables)

Also, it'd be clearer to break this string out into a constant somewhere (`PixeltableBot.SYSTEM_PROMPT` or some such)
</blockquote></details>

Moved out. Done.
___
*[`examples/context-aware-discord-bot/bot.py` line 269 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXc2ch7c8r-x4YKncn:-OBd8OWIE64IEuqwJAwV:bss4a2b) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/bot.py#L269)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

i don't think this is what you want; it will set `token` to the string `'OPENAI_API_KEY'` if `DISCORD_TOKEN` is not found in the environment. Just do

```python
token = os.getenv('DISCORD_TOKEN')
```

if `OPENAI_API_KEY` is missing, Pixeltable will complain later.
</blockquote></details>

Removed.
___
*[`examples/context-aware-discord-bot/message_formatter.py` line 14 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBXc_NrCg8-ffx_uanN:-OBd8cU224Y-EvdJ8NGM:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/679bb3768ca5f77fd664a632a705e35a714d8852/examples/context-aware-discord-bot/message_formatter.py#L14)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

use lowercase `list`, `dict` (the upper case variants are only necessary for Python 3.8 compatibility)
</blockquote></details>

Done.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/367)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @pierrebrunelle)

___
*[`examples/context-aware-discord-bot/bot.py` line 273 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBlOBQE4vxwy6rYwVTh:-OBlOBQE4vxwy6rYwVTi:bd5lac1) ([raw file](https://github.com/pixeltable/pixeltable/blob/ffd3810dc335830952ce0daa897fad66af74f45b/examples/context-aware-discord-bot/bot.py#L273)):*
> ```Python
>     load_dotenv()
>     token = os.getenv('DISCORD_TOKEN')
>     if not token:
> ```

Preferred style here is `if token is None:`
___
*[`examples/context-aware-discord-bot/message_formatter.py` line 3 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/367#-OBlOIjp1XSLhllIkKj9:-OBlOIjp1XSLhllIkKjA:b8np8yv) ([raw file](https://github.com/pixeltable/pixeltable/blob/ffd3810dc335830952ce0daa897fad66af74f45b/examples/context-aware-discord-bot/message_formatter.py#L3)):*
> ```Python
> import discord
> from datetime import datetime
> from typing import List, Dict
> ```

this import can be removed now

**Pull request merged**
