### PR TITLE
Performance improvements for Table.batch_update()

### PR DESCRIPTION
**Pull request by mkornacker**
- batch_update() now runs a single ExecNode tree and all updates are covered by a single transaction,
resulting in a single new table version
- new ExecNodes RowUpdateNode and SqlLookupNode

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)* status: 0 of 7 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/plan.py` line 296 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bxHNJ2ooWOWJ4Enye:-O2bxHNJ2ooWOWJ4Enyf:b5df6v8) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L296)):*
> ```Python
>             batch: list[dict[catalog.Column, exprs.Expr]], rowids: list[tuple[int, ...]],
>             cascade: bool
>     ) -> Tuple[exec.ExecNode, List[str], List[catalog.Column]]:
> ```

It'd be better to use a `namedtuple` (or `dataclass`) for the return value, rather than having to explain the meaning of the tuple in a comment.
___
*[`pixeltable/plan.py` line 300 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bxmwmENG0NlrmhY2k:-O2bxmwmENG0NlrmhY2l:b38ig51) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L300)):*
> ```Python
>         Returns:
>         - root node of the plan
>         - list of qualified column names that are getting updated
> ```

Why are these given as column names rather than `Column` objects?
___
*[`pixeltable/plan.py` line 337 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vqIaB6m8TTNPCZvO2:-O2vqIaB6m8TTNPCZvO3:b-yjunmb) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L337)):*
> ```Python
>         # ExecNode tree:
>         # - SqlLookupNode to retrieve the existing rows
>         # - ExprEvalNode to evaluate the remaining output exprs
> ```

Also a RowUpdateNode?
___
*[`pixeltable/plan.py` line 350 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vqfSY3x5boMYIx_OV:-O2vqfSY3x5boMYIx_OW:bnfam5r) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L350)):*
> ```Python
>         all_base_cols = copied_cols + list(updated_cols) + list(recomputed_base_cols)  # same order as select_list
>         row_builder.substitute_exprs(select_list, remove_duplicates=False)
>         [plan.row_builder.add_table_column(col, select_list[i].slot_idx) for i, col in enumerate(all_base_cols)]
> ```

What is this doing? It's very odd to use a comprehension when the collection isn't actually getting used for anything. Preferable is

```python
for i, col in enumerate(all_base_cols):
    plan.row_builder.add_table_column(col, select_list[i].slot_idx)
```
___
*[`pixeltable/plan.py` line 357 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vrYs29nlH1HoNlFL9:-O2vrYs29nlH1HoNlFLA:basryit) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L357)):*
> ```Python
>         plan.set_ctx(ctx)
>         recomputed_user_cols = [c for c in recomputed_cols if c.name is not None]
>         return plan, [f'{c.tbl.name}.{c.name}' for c in list(updated_cols) + recomputed_user_cols], recomputed_user_cols
> ```

I'd prefer a `c.qualified_name` property, rather than doing the string construction here.
___
*[`pixeltable/catalog/table_version.py` line 757 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vrmjG6d5LLmsdfFK7:-O2vrmjG6d5LLmsdfFK8:bjz18r5) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/catalog/table_version.py#L757)):*
> ```Python
>                 raise excs.Error(f'Update specification: dict key must be column name, got {col_name!r}')
>             if col_name == _ROWID_COLUMN_NAME:
>                 assert len(val) == len(self.store_tbl.rowid_columns())
> ```

I think the comment "ignore pseudo-column _rowid" is useful; I'd advocate for keeping it. A comment explaining these assertions would be helpful too
___
*[`pixeltable/exec/row_update_node.py` line 22 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bx6E5540vmyk5FOX-:-O2bx6E5540vmyk5FOX0:bb5zqse) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/row_update_node.py#L22)):*
> ```Python
>     def __init__(
>             self, tbl: catalog.TableVersionPath, key_vals_batch: list[tuple], is_rowid_key: bool,
>             col_vals_batch: list[Dict[str, Any]], row_builder: exprs.RowBuilder, input: ExecNode,
> ```

lowercase `dict`
___
*[`pixeltable/exec/sql_node.py` line 16 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vti8J9yHYmxrMWZEk:-O2vti8J9yHYmxrMWZEl:b5a4484) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/sql_node.py#L16)):*
> ```Python
> _logger = logging.getLogger('pixeltable')
> 
> class SqlNode(ExecNode):
> ```

I started to read this carefully and then stopped; I assume (except for `SqlLookupNode`) it's just refactored from the old `SqlScanNode` to break it into a super/subclass pattern. But lmk if there are parts of it that should be reviewed.
___
*[`pixeltable/exec/sql_node.py` line 20 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vsbo57LPjgEZ0qUrw:-O2vsbo57LPjgEZ0qUrx:bgagvvx) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/sql_node.py#L20)):*
> ```Python
> 
>     def __init__(
>             self, tbl: catalog.TableVersionPath, row_builder: exprs.RowBuilder,
> ```

Style note, I find it unsettling that `tbl` is used variously for instances of `Table`, `TableVersion`, or `TableVersionPath`. maybe consider standardizing on different variable names for each? `tvp` would be crystal clear for an instance of `TableVersionPath` (with the added benefit that it has no other meaning)
___
*[`pixeltable/exec/sql_node.py` line 49 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vt0WJEyqClSUTYA36:-O2vt0WJEyqClSUTYA37:b-898um9) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/sql_node.py#L49)):*
> ```Python
>         sql_select_list = [e.sql_expr() for e in self.sql_exprs]
>         assert len(sql_select_list) == len(self.sql_exprs)
>         assert all([e is not None for e in sql_select_list])
> ```

it's not necessary to instantiate a list here

```python
assert all(e is not None for e in sql_select_list)
```

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)* status: 0 of 7 files reviewed, 11 unresolved discussions (waiting on @mkornacker)

___
*[`tests/test_table.py` line 624 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vumEE0i7O_qZ9S-nG:-O2vumEE0i7O_qZ9S-nH:b-4k89cs) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/tests/test_table.py#L624)):*
> ```Python
>         _ = t2.show(n=0)
> 
>     def test_batch_update(self, test_tbl: pxt.Table) -> None:
> ```

Does this PR solve the issue of batch_update columns belonging to multiple base tables? If so, we should add a test for that scenario

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)* status: 0 of 7 files reviewed, 11 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/plan.py` line 296 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bxHNJ2ooWOWJ4Enye:-O3rn615Dw-K9oRCWnx8:b-xbtxge) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L296)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It'd be better to use a `namedtuple` (or `dataclass`) for the return value, rather than having to explain the meaning of the tuple in a comment.
</blockquote></details>

Out of scope, that's something to address in a restructuring of the entire module.
___
*[`pixeltable/plan.py` line 300 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bxmwmENG0NlrmhY2k:-O3rn5BDDGEQ8L2bwAWQ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L300)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Why are these given as column names rather than `Column` objects?
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 337 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vqIaB6m8TTNPCZvO2:-O3oGKtl75Cy4mioefkb:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L337)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Also a RowUpdateNode?
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 350 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vqfSY3x5boMYIx_OV:-O3rxNMD8r2J9P4Z0S87:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L350)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

What is this doing? It's very odd to use a comprehension when the collection isn't actually getting used for anything. Preferable is

```python
for i, col in enumerate(all_base_cols):
    plan.row_builder.add_table_column(col, select_list[i].slot_idx)
```
</blockquote></details>

Done.
___
*[`pixeltable/plan.py` line 357 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vrYs29nlH1HoNlFL9:-O3rxMwq1CQ_Q0JzDD3g:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/plan.py#L357)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'd prefer a `c.qualified_name` property, rather than doing the string construction here.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table_version.py` line 757 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vrmjG6d5LLmsdfFK7:-O3oGcRg37dRkQyBGHC0:by3csm0) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/catalog/table_version.py#L757)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I think the comment "ignore pseudo-column _rowid" is useful; I'd advocate for keeping it. A comment explaining these assertions would be helpful too
</blockquote></details>

But it's not getting ignored anymore.

Added comment.
___
*[`pixeltable/exec/row_update_node.py` line 22 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2bx6E5540vmyk5FOX-:-O3oGm2n39heyY8fCaQQ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/row_update_node.py#L22)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

lowercase `dict`
</blockquote></details>

Done.
___
*[`pixeltable/exec/sql_node.py` line 20 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vsbo57LPjgEZ0qUrw:-O3oGssV18MwmJDZrQdb:bqmig9u) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/sql_node.py#L20)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Style note, I find it unsettling that `tbl` is used variously for instances of `Table`, `TableVersion`, or `TableVersionPath`. maybe consider standardizing on different variable names for each? `tvp` would be crystal clear for an instance of `TableVersionPath` (with the added benefit that it has no other meaning)
</blockquote></details>

out of scope
___
*[`pixeltable/exec/sql_node.py` line 49 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vt0WJEyqClSUTYA36:-O3oH21V3SBWDyR-kpNQ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/pixeltable/exec/sql_node.py#L49)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

it's not necessary to instantiate a list here

```python
assert all(e is not None for e in sql_select_list)
```
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 624 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vumEE0i7O_qZ9S-nG:-O3oH3d60hhKEgNhYD-c:bep0mb6) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/tests/test_table.py#L624)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Does this PR solve the issue of batch_update columns belonging to multiple base tables? If so, we should add a test for that scenario
</blockquote></details>

It does not.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/globals.py` line 26 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O490w208psWfANsVdL8:-O490w208psWfANsVdL9:bgja7rp) ([raw file](https://github.com/pixeltable/pixeltable/blob/6f4f2d673c029be5677cf61779cb2f3d83954f98/pixeltable/catalog/globals.py#L26)):*
> ```Python
>         self.num_computed_values += other.num_computed_values
>         self.num_excs += other.num_excs
>         self.updated_cols = list(set(self.updated_cols + other.updated_cols))
> ```

Note that this will scramble the order of the list in a nondeterministic way. You can deduplicate a list in an order-preserving way with
```
list(dict.fromkeys(orig_list))
```
Maybe not super important here, but might be nice to have deterministic output
___
*[`tests/test_table.py` line 624 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vumEE0i7O_qZ9S-nG:-O49208UCUEdIbh1855f:b-y15kaf) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/tests/test_table.py#L624)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

It does not.
</blockquote></details>

Hmm, then I think it'd be useful to have a test that tries to do this, and asserts that some useful error message is returned (as opposed to some unexpected/undefined behavior). That would also help document that we need to address this in the future

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/229)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/globals.py` line 26 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O490w208psWfANsVdL8:-O4Glulq5RuzivIfmNHZ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/6f4f2d673c029be5677cf61779cb2f3d83954f98/pixeltable/catalog/globals.py#L26)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Note that this will scramble the order of the list in a nondeterministic way. You can deduplicate a list in an order-preserving way with
```
list(dict.fromkeys(orig_list))
```
Maybe not super important here, but might be nice to have deterministic output
</blockquote></details>

Done.
___
*[`tests/test_table.py` line 624 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/229#-O2vumEE0i7O_qZ9S-nG:-O4GlygV4NybwWWFpi2n:bhykyxj) ([raw file](https://github.com/pixeltable/pixeltable/blob/57b467addc16236f0c1d3d5d4628b9da1385fd53/tests/test_table.py#L624)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Hmm, then I think it'd be useful to have a test that tries to do this, and asserts that some useful error message is returned (as opposed to some unexpected/undefined behavior). That would also help document that we need to address this in the future
</blockquote></details>

It would be something random right now. I'd rather fix this and create a test for it then.

**Pull request merged**
