### PR TITLE
CachePrefetchNode now fetches asynchronously

### PR DESCRIPTION
**Pull request by mkornacker**

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/cache_prefetch_node.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyIgO_C2iv4wWJ7DiT:-OAyIgO_C2iv4wWJ7DiU:bm1z2k0) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L43)):*
> ```Python
>     batch_tbl_version: Optional[catalog.TableVersion]  # needed to construct output batches
>     num_returned_rows: int
>     ready_rows: deque[Optional[exprs.DataRow]]  # the implied row idx of ready_rows[0] is num_returned_rows
> ```

add code comment: describe the meaning of ready_rows vs. in_flight_rows
___
*[`pixeltable/exec/cache_prefetch_node.py` line 107 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyHJem9DZJY6QPlIdT:-OAyHJem9DZJY6QPlIdU:b65fyw0) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L107)):*
> ```Python
>                     return
> 
>     def _num_pending_rows(self) -> int:
> ```

standard Python convention is to prefix method names with a double underscore (`__num_pending_rows(self)`) unless they're intended to be accessed from outside the class or by a subclass
___
*[`pixeltable/exec/cache_prefetch_node.py` line 111 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyNP913gm301jVsx1f:-OAyNP913gm301jVsx1g:b-unoy9g) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L111)):*
> ```Python
> 
>     def _has_ready_batch(self) -> bool:
>         """True if the first BATCH_SIZE entries in ready_rows are all non-None"""
> ```

... and there are at least BATCH_SIZE entries in ready_rows.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 113 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyJ-JY8chv2-3pBTpX:-OAyJ-JY8chv2-3pBTpY:bao97gq) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L113)):*
> ```Python
>         """True if the first BATCH_SIZE entries in ready_rows are all non-None"""
>         return (
>             sum(1 for row in itertools.islice(self.ready_rows, self.BATCH_SIZE) if row is not None) == self.BATCH_SIZE
> ```

more succinct is:

```python
sum(row is not None for row in itertools.islice(self.ready_rows, self.BATCH_SIZE))
```

but maybe just combine this with `_ready_batch_size`?

```python
return self.__ready_batch_size() >= self.BATCH_SIZE
```

(and move the BATCH_SIZE bound sentinel into _ready_batch_size)
___
*[`pixeltable/exec/cache_prefetch_node.py` line 116 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyOyL88-LD6Bq2gD3P:-OAyOyL88-LD6Bq2gD3Q:blbp0hi) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L116)):*
> ```Python
>         )
> 
>     def _ready_batch_size(self) -> int:
> ```

`__ready_row_count()` or `__num_ready_rows()` is more logical to me since to avoid confusion with `BATCH_SIZE` (it took me a minute or two to parse this out)
___
*[`pixeltable/utils/s3.py` line 1 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAx88SV7q5dDaynV_Vv:-OAx88SV7q5dDaynV_Vw:b-jkyjn) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/utils/s3.py#L1)):*
> ```Python
> from typing import Any, Optional
> ```

spurious import?
___
*[`tests/utils.py` line 351 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyR7V87_qIJdnaTKlz:-OAyR7V87_qIJdnaTKm-:b-dx2za) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L351)):*
> ```Python
>         image.close()
> 
> def get_multimedia_commons_video_uris(n: int = 10) -> list[str]:
> ```

So where is this being used? I don't see any new tests or any changes to tests to utilize it.

There should probably be a test that fetches > BATCH_SIZE files.

Also, a test that inserts the same URL multiple times to ensure that the `URL -> list` mapping logic is correct
___
*[`tests/utils.py` line 360 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAx8ahs5aEF-BK3VcQg:-OAx8ahs5aEF-BK3VcQh:b-orpi56) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L360)):*
> ```Python
>     import botocore
>     try:
>         boto3.Session().get_credentials().get_frozen_credentials()
> ```

why not use `utils.s3.get_client()` here?

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exec/cache_prefetch_node.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyIgO_C2iv4wWJ7DiT:-OAyepzp9DxceTbWvSWj:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L43)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

add code comment: describe the meaning of ready_rows vs. in_flight_rows
</blockquote></details>

Done.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 107 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyHJem9DZJY6QPlIdT:-OAyeyipD9muFi0XSeFC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L107)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

standard Python convention is to prefix method names with a double underscore (`__num_pending_rows(self)`) unless they're intended to be accessed from outside the class or by a subclass
</blockquote></details>

Done.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 111 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyNP913gm301jVsx1f:-OAyfCo4879jkB_OUBjC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L111)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

... and there are at least BATCH_SIZE entries in ready_rows.
</blockquote></details>

Done.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 113 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyJ-JY8chv2-3pBTpX:-OAyg74t3gT8NVuE6k7e:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L113)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

more succinct is:

```python
sum(row is not None for row in itertools.islice(self.ready_rows, self.BATCH_SIZE))
```

but maybe just combine this with `_ready_batch_size`?

```python
return self.__ready_batch_size() >= self.BATCH_SIZE
```

(and move the BATCH_SIZE bound sentinel into _ready_batch_size)
</blockquote></details>

Done.
___
*[`pixeltable/exec/cache_prefetch_node.py` line 116 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyOyL88-LD6Bq2gD3P:-OAyg6oWC-4rpd1VNUUW:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L116)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`__ready_row_count()` or `__num_ready_rows()` is more logical to me since to avoid confusion with `BATCH_SIZE` (it took me a minute or two to parse this out)
</blockquote></details>

Done.
___
*[`pixeltable/utils/s3.py` line 1 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAx88SV7q5dDaynV_Vv:-OAygBql12WMHuKQ0bXa:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/utils/s3.py#L1)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

spurious import?
</blockquote></details>

Done.
___
*[`tests/utils.py` line 351 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyR7V87_qIJdnaTKlz:-OAygEn36SrITSl-lQRw:b-dw88wv) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L351)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

So where is this being used? I don't see any new tests or any changes to tests to utilize it.

There should probably be a test that fetches > BATCH_SIZE files.

Also, a test that inserts the same URL multiple times to ensure that the `URL -> list` mapping logic is correct
</blockquote></details>

I used it in a scale test, but I didn't want to add that test. I think this is useful so I'd prefer to just leave it here.
___
*[`tests/utils.py` line 360 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAx8ahs5aEF-BK3VcQg:-OAygz8ZBhXNuACbMNNF:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L360)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

why not use `utils.s3.get_client()` here?
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/exec/cache_prefetch_node.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyIgO_C2iv4wWJ7DiT:-OB2iRdR3536VpWuCSlQ:b-f9j59h) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L43)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i don't see it?
___
*[`tests/utils.py` line 351 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyR7V87_qIJdnaTKlz:-OB2iaOG8Qq1P8Ff_Ffc:b-6bapfp) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L351)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I used it in a scale test, but I didn't want to add that test. I think this is useful so I'd prefer to just leave it here.
</blockquote></details>

Ok, but shouldn't we have some unit tests also?

See my above comment - I think at minimum we should have a test that fetches > BATCH_SIZE files and a test that inserts the same URL multiple times (which could be the same test)

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/exec/cache_prefetch_node.py` line 43 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyIgO_C2iv4wWJ7DiT:-OB6rNo56WaPRa10AxWD:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/pixeltable/exec/cache_prefetch_node.py#L43)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

i don't see it?
</blockquote></details>

Done.
___
*[`tests/utils.py` line 351 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OAyR7V87_qIJdnaTKlz:-OB6vVbgCOgND0X6kmP3:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/a2668a451df50f4803fe54c558db9438ab698526/tests/utils.py#L351)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Ok, but shouldn't we have some unit tests also?

See my above comment - I think at minimum we should have a test that fetches > BATCH_SIZE files and a test that inserts the same URL multiple times (which could be the same test)
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/354)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @mkornacker)

___
*[`tests/test_table.py` line 751 at r7](https://reviewable.io/reviews/pixeltable/pixeltable/354#-OBBZoLm0tfUGV3I9k9n:-OBBZoLm0tfUGV3I9k9o:b-7cseru) ([raw file](https://github.com/pixeltable/pixeltable/blob/44a1fc1350432c038c1d73f310348a3ad30b0660/tests/test_table.py#L751)):*
> ```Python
>         random.shuffle(uris)
> 
>         # TODO: give parallel test runners their own cache
> ```

You can remove this TODO. Parallel test runners already have their own cache.

**Review by aaron-siegel — APPROVED** [review]

**Pull request merged**
