### PR TITLE
Index tutorial

### PR DESCRIPTION
**Pull request by mkornacker**
New How-To: embedding-indexes.ipynb

Plus: some related API enhancements and bug fixes

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/214)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/214)* status: 0 of 14 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`docs/release/howto/embedding-indexes.ipynb` line 19 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tv5bQ5-yRd0hClYjE:-O1tv5bQ5-yRd0hClYjF:b2ec7t2) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L19)):*
> ```
>     "* Indexing in Pixeltable is declarative\n",
>     "  - you create an index on a column and supply the embedding functions you want to use (for inserting data into the index as well as lookups)\n",
>     "  - Pixeltable maintains the index in response to any kind of update of the indexed table (ie, `insert()`/`update()`/`delete()`)\n",
> ```

"ie" is normally written with periods: "i.e."
___
*[`docs/release/howto/embedding-indexes.ipynb` line 133 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tvdt19zbUMEfVgop5:-O1tvdt19zbUMEfVgop6:b-qn4hmc) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L133)):*
> ```
>     "To create and populate an index, we call [`Table.add_embedding_index()`](https://pixeltable.github.io/pixeltable/api/table/#pixeltable.Table.add_embedding_index) and tell it which functions to use to create string and image embeddings. That definition is persisted as part of the table's metadata, which allows Pixeltable to maintain the index in response to updates to the table.\n",
>     "\n",
>     "We're going to use [CLIP](https://huggingface.co/docs/transformers/en/model_doc/clip), for which the Hugging Face version is already available in Pixeltable as a function under [`pixeltable.functions.huggingface`](https://pixeltable.github.io/pixeltable/api/functions/huggingface/#pixeltable.functions.huggingface). However, you can use any embedding function you like, via Pixeltable's UDF mechanism (which is described in detail [here](https://pixeltable.readme.io/docs/user-defined-functions-udfs))."
> ```

I don't love links with the hypertext "here"; I find it clearer to write something more descriptive, e.g.:

```
which is described in detail in the [User-Defined Functions](https://...) in-depth guide.
```

I do appreciate all the cross-links to other tutorials!
___
*[`docs/release/howto/embedding-indexes.ipynb` line 160 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1twS4Q1ip2DehQDHmD:-O1twS4Q1ip2DehQDHmE:b-p6jf55) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L160)):*
> ```
>     "\n",
>     "# create a udf that takes a single image, to use as an embedding function\n",
>     "@pxt.expr_udf\n",
> ```

I still don't love `@pxt.expr_udf`; any interest in changing it to `@pxt.expression`?
___
*[`docs/release/howto/embedding-indexes.ipynb` line 174 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1twhseBS0f4UzHCokC:-O1twhseBS0f4UzHCokD:b-8ces6a) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L174)):*
> ```
>    "source": [
>     "The first parameter of `add_embedding_index()` is the name of the column being indexed. Keyword parameters are:\n",
>     "* `string_embed`: Pixeltable `Function` to compute embeddings for `StringType` data  **TODO: why does the _ disappear?**\n",
> ```

Remove TODO before publishing (I'm not even sure what it's referring to?)
___
*[`docs/release/howto/embedding-indexes.ipynb` line 228 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txS30AjwcAiJ2M-m-:-O1txS30AjwcAiJ2M-m0:btguh51) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L228)):*
> ```
>     "We then call the `similarity()` pseudo-function as a method on the indexed column and apply `order_by()` and `limit()`. We used the default cosine distance when we created the index, so we're going to order by descending similarity (`order_by(..., asc=False)`):\n",
>     "\n",
>     "**TODO**: link to similarity()"
> ```

Is the intent to link to the API reference here?
___
*[`docs/release/howto/embedding-indexes.ipynb` line 283 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txe3zDGLHYPhVYy0W:-O1txe3zDGLHYPhVYy0X:b-n34l6f) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L283)):*
> ```
>     "sim = imgs.img.similarity(sample_img)\n",
>     "# use 'similarity()' in the order_by() clause and apply a limit in order to utilize the index\n",
>     "res = imgs.order_by(sim, asc=False).limit(2).select(imgs.img, sim, imgs.bucket, imgs.color).collect()\n",
> ```

Give the similarity column a name (here and in the subsequent usage) in preference to `col_1`
___
*[`docs/release/howto/embedding-indexes.ipynb` line 476 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txxQh1dxLCQ3ySy6R:-O1txxQh1dxLCQ3ySy6S:b-l474wa) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L476)):*
> ```
>     "We can create multiple embedding indexes on the same column, utilizing different embedding models. In order to use a specific index in a query, we need to assign it a name and then use that name in the query.\n",
>     "\n",
>     "To illustrate this, let's create a table with text (taken from the Wikipedia article on [Pablo Picasso](https://en.wikipedia.org/wiki/Pablo_Picasso):"
> ```

Closing paren is missing
___
*[`docs/release/howto/embedding-indexes.ipynb` line 530 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1ty8AzBRpe6044vTJ0:-O1ty8AzBRpe6044vTJ1:bw825u1) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L530)):*
> ```
>    "metadata": {},
>    "source": [
>     "When calling [`add_embedding_index()`](https://pixeltable.github.io/pixeltable/api/table/#pixeltable.Table.add_embedding_index), we now specify the index name (`idx_name`) directly. If it is not specified, the Pixeltable will assign a name (typically `idx<#>`)."
> ```

s/the Pixeltable/Pixeltable/

Also, i find `idx<#>` confusing, maybe just say "typically something like `idx0`".
___
*[`docs/release/howto/embedding-indexes.ipynb` line 623 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tyUb_EyzPAooY2XA7:-O1tyUb_EyzPAooY2XA8:b-tj01xb) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L623)):*
> ```
>     "## Deleting an index\n",
>     "\n",
>     "To delete an index, call [`Table.drop_embedding_index()`](https://pixeltable.github.io/pixeltable/api/table/#pixeltable.Table.drop_embedding_index):"
> ```

What if it's the only index and I didn't give it a name?
___
*[`pixeltable/metadata/converters/convert_17.py` line 17 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1turyDD3pbWuvxAEAD:-O1turyDD3pbWuvxAEAE:b32qxe7) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/pixeltable/metadata/converters/convert_17.py#L17)):*
> ```Python
> def __update_table_md(table_md: dict) -> None:
>     # key changes in IndexMd.init_args: img_embed -> image_embed, txt_embed -> string_embed
>     if len(table_md['index_md']) == 0:
> ```

This seems unnecessary (if the condition is true, the succeeding for loop is vacuous anyway)

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/214)* status: 0 of 14 files reviewed, 10 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/howto/embedding-indexes.ipynb` line 19 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tv5bQ5-yRd0hClYjE:-O21tUH6BHk7S_Fke7xY:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L19)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"ie" is normally written with periods: "i.e."
</blockquote></details>

Done.
___
*[`docs/release/howto/embedding-indexes.ipynb` line 133 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tvdt19zbUMEfVgop5:-O21tru78WwU-qUIZL9e:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L133)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I don't love links with the hypertext "here"; I find it clearer to write something more descriptive, e.g.:

```
which is described in detail in the [User-Defined Functions](https://...) in-depth guide.
```

I do appreciate all the cross-links to other tutorials!
</blockquote></details>

Done.
___
*[`docs/release/howto/embedding-indexes.ipynb` line 160 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1twS4Q1ip2DehQDHmD:-O21tsgL18SkyL9yneKl:bqmig9u) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L160)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I still don't love `@pxt.expr_udf`; any interest in changing it to `@pxt.expression`?
</blockquote></details>

out of scope
___
*[`docs/release/howto/embedding-indexes.ipynb` line 174 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1twhseBS0f4UzHCokC:-O21unzgBNf6pYuqgkTX:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L174)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Remove TODO before publishing (I'm not even sure what it's referring to?)
</blockquote></details>

Done.
___
*[`docs/release/howto/embedding-indexes.ipynb` line 283 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txe3zDGLHYPhVYy0W:-O21ve-kET6ihOETOTBL:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L283)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Give the similarity column a name (here and in the subsequent usage) in preference to `col_1`
</blockquote></details>

Done.

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/214)* status: 0 of 14 files reviewed, 10 unresolved discussions (waiting on @aaron-siegel)

___
*[`docs/release/howto/embedding-indexes.ipynb` line 228 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txS30AjwcAiJ2M-m-:-O21wbgeDgfSuAHxAdf4:b2nhswy) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L228)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Is the intent to link to the API reference here?
</blockquote></details>

Yes
___
*[`docs/release/howto/embedding-indexes.ipynb` line 476 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1txxQh1dxLCQ3ySy6R:-O21wK_H85yHf1kz5cQI:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L476)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Closing paren is missing
</blockquote></details>

Done.
___
*[`docs/release/howto/embedding-indexes.ipynb` line 530 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1ty8AzBRpe6044vTJ0:-O21wRQu5t8p6_nQlEbC:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L530)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

s/the Pixeltable/Pixeltable/

Also, i find `idx<#>` confusing, maybe just say "typically something like `idx0`".
</blockquote></details>

Done.
___
*[`docs/release/howto/embedding-indexes.ipynb` line 623 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1tyUb_EyzPAooY2XA7:-O21wa8P5LFQLRNmjrYt:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/docs/release/howto/embedding-indexes.ipynb#L623)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

What if it's the only index and I didn't give it a name?
</blockquote></details>

Done.

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/214)* status: 0 of 14 files reviewed, 10 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/metadata/converters/convert_17.py` line 17 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/214#-O1turyDD3pbWuvxAEAD:-O21wkCEC7oJ2ZJo56aR:bpr2r4i) ([raw file](https://github.com/pixeltable/pixeltable/blob/568740f18f49f73cb208feb459c6be60aa0f8964/pixeltable/metadata/converters/convert_17.py#L17)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This seems unnecessary (if the condition is true, the succeeding for loop is vacuous anyway)
</blockquote></details>

That's intentional, to avoid indentation.

**Review by aaron-siegel — APPROVED** [review]

**Pull request merged**
