### PR TITLE
Type-checking groundwork

### PR DESCRIPTION
**Pull request by aaron-siegel**
This fixes up `type_system.py` and gets mypy type checking working for all the base dir py files (`pixeltable/*.py`) except `plan.py`.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/261)

**Review by mkornacker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/261)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

___
*[`pixeltable/store.py` line 39 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/261#-O50mf1z79vifMz57spY:-O50mf1z79vifMz57spZ:b-tctz18) ([raw file](https://github.com/pixeltable/pixeltable/blob/568e76965778fe9cdaad4ca443a0bbc9fcae4d4a/pixeltable/store.py#L39)):*
> ```Python
>         self.sa_md = sql.MetaData()
>         self.sa_tbl: Optional[sql.Table] = None
>         self.base = None if tbl_version.base is None else tbl_version.base.store_tbl
> ```

Comment: why here and not in the subclass that needs it?

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/261)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @mkornacker)

___
*[`pixeltable/store.py` line 39 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/261#-O50mf1z79vifMz57spY:-O51NML0DEDLttLA8_ea:bo8hln3) ([raw file](https://github.com/pixeltable/pixeltable/blob/568e76965778fe9cdaad4ca443a0bbc9fcae4d4a/pixeltable/store.py#L39)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Comment: why here and not in the subclass that needs it?
</blockquote></details>

It gets referenced in `_versions_clause`, which belongs to `StoreBase`.

**Review by mkornacker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/261)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @aaron-siegel)

___
*[`pixeltable/store.py` line 39 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/261#-O50mf1z79vifMz57spY:-O51YnpC1uO7qAigGsW6:beh5zsh) ([raw file](https://github.com/pixeltable/pixeltable/blob/568e76965778fe9cdaad4ca443a0bbc9fcae4d4a/pixeltable/store.py#L39)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

It gets referenced in `_versions_clause`, which belongs to `StoreBase`.
</blockquote></details>

I meant: add explanation as a comment

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/261)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @mkornacker)

___
*[`pixeltable/store.py` line 39 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/261#-O50mf1z79vifMz57spY:-O54uvhT6NYfwzEjrc90:byqvgvf) ([raw file](https://github.com/pixeltable/pixeltable/blob/568e76965778fe9cdaad4ca443a0bbc9fcae4d4a/pixeltable/store.py#L39)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

I meant: add explanation as a comment
</blockquote></details>

I see. Done

**Pull request merged**
