### PR TITLE
Test utility to verify query results after catalog reload

### PR DESCRIPTION
**Pull request by mkornacker**
This should be used in tests that change table metadata that is relevant for running queries.

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/365)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/365)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`tests/conftest.py` line 92 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSnhU_9P0-jpoR-Pvf:-OBSnhU_9P0-jpoR-Pvg:b-gozt0u) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/conftest.py#L92)):*
> ```Python
> 
> @pytest.fixture(scope='function')
> def reload_test(init_env) -> ReloadTester:
> ```

calling this `reload_tester` is more logical (the fixture is a tester, not a test)

or we could give it a nice short name, like `rt`, since we'll be using it a lot...
___
*[`tests/utils.py` line 383 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoQm9Bqe539XRVbbY:-OBSoQmA9rnBJXIhY67s:bts1ij) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L383)):*
> ```Python
>         assert r1.schema.keys() == r2.schema.keys()
>     for r1_col, r2_col in zip(r1.schema, r2.schema):
>         # only compare column values
> ```

it's no longer an "only"
___
*[`tests/utils.py` line 528 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSp3wN1PA_i7H8DV9Y:-OBSp3wN1PA_i7H8DV9Z:b-9h3hwg) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L528)):*
> ```Python
>     """Utility to verify that queries return identical results after a catalog reload"""
> 
>     df_info: list[tuple[dict[str, Any], DataFrameResultSet]]
> ```

add comment explaining what this is
___
*[`tests/utils.py` line 539 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoxxRD0hzBLH_RTg-:-OBSoxxRD0hzBLH_RTg0:bmwq90z) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L539)):*
> ```Python
>         return result_set
> 
>     def run_test(self, clear: bool = True) -> None:
> ```

use a more specific method name such as `reload_and_compare()`
___
*[`tests/utils.py` line 545 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSobav0is0W1LQi5Bn:-OBSobav0is0W1LQi5Bo:b-m4m3sf) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L545)):*
> ```Python
>             result_set = df.collect()
>             try:
>                 assert_resultset_eq(result_set, result_set, compare_col_names=True)
> ```

umm, there's some serious variable shadowing going on here? you're comparing `result_set` to itself? :)
___
*[`tests/utils.py` line 548 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoo0v-XJhklaSsqPc:-OBSoo0v-XJhklaSsqPd:b1pb8vq) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L548)):*
> ```Python
>             except Exception as e:
>                 s = f'Reload test failed for query:\n{df}\n{e}'
>                 raise RuntimeError(s)
> ```

`raise RuntimeError(s) from e`

to join the stack traces
___
*[`tests/utils.py` line 549 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSpQQmAVmmjr2oeyin:-OBSpQQmAVmmjr2oeyio:bin01f7) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L549)):*
> ```Python
>                 s = f'Reload test failed for query:\n{df}\n{e}'
>                 raise RuntimeError(s)
>         if clear:
> ```

i'd prefer this be a separate method (`ReloadTester.clear()`) rather than an optional parameter

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/365)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @aaron-siegel)

___
*[`tests/conftest.py` line 92 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSnhU_9P0-jpoR-Pvf:-OC-pErq3NqucgsF0bBf:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/conftest.py#L92)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

calling this `reload_tester` is more logical (the fixture is a tester, not a test)

or we could give it a nice short name, like `rt`, since we'll be using it a lot...
</blockquote></details>

Done.
___
*[`tests/utils.py` line 383 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoQm9Bqe539XRVbbY:-OC-pNYDD4mzHtkeYZCb:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L383)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

it's no longer an "only"
</blockquote></details>

Done.
___
*[`tests/utils.py` line 528 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSp3wN1PA_i7H8DV9Y:-OC-p_CbEAnZH6ifaBuf:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L528)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

add comment explaining what this is
</blockquote></details>

Done.
___
*[`tests/utils.py` line 539 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoxxRD0hzBLH_RTg-:-OC-qR-_BbsSq2HaM-7h:bb6un1j) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L539)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

use a more specific method name such as `reload_and_compare()`
</blockquote></details>

Done
___
*[`tests/utils.py` line 545 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSobav0is0W1LQi5Bn:-OC-pq2O6OMzmdsdusFp:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L545)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

umm, there's some serious variable shadowing going on here? you're comparing `result_set` to itself? :)
</blockquote></details>

Done.
___
*[`tests/utils.py` line 548 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSoo0v-XJhklaSsqPc:-OC-pvP07Dk0togSv8E9:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L548)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

`raise RuntimeError(s) from e`

to join the stack traces
</blockquote></details>

Done.
___
*[`tests/utils.py` line 549 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSpQQmAVmmjr2oeyin:-OC-q3_a-zx3KmpFVoiN:b-7towtx) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L549)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

i'd prefer this be a separate method (`ReloadTester.clear()`) rather than an optional parameter
</blockquote></details>

Also added as separate method. I'm leaving the parameter in place in order to minimize boilerplate code.

**Review by aaron-siegel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/365)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mkornacker)

___
*[`tests/utils.py` line 549 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OBSpQQmAVmmjr2oeyin:-OC28VKwE7UGLhOUxMHk:b-wf0cop) ([raw file](https://github.com/pixeltable/pixeltable/blob/f2099684117bb76cc93d967f7112e00b19c62d79/tests/utils.py#L549)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Also added as separate method. I'm leaving the parameter in place in order to minimize boilerplate code.
</blockquote></details>

I have a moderately strong preference for getting rid of the parameter. It's an unusual pattern that overloads the behavior of this function, and I wouldn't consider one extra call to `clear()` to be boilerplate code.

If you really must keep the parameter, let's at least call it "clear_after_run" or some such?
___
*[`tests/test_index.py` line 60 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/365#-OC2945j0iWNhd0eyFCk:-OC2945j0iWNhd0eyFCl:bq1ghg7) ([raw file](https://github.com/pixeltable/pixeltable/blob/fd6681d36a91b5cea103bb9143bc154927b40966/tests/test_index.py#L60)):*
> ```Python
>             t.drop_column('sim')
> 
>             reload_tester.run_reload_test(clear=True)
> ```

Isn't `clear=True` the default?

**Pull request merged**
