### PR TITLE
Adding cross-links to docstrings.

### PR DESCRIPTION
**Pull request by mkornacker**

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/262)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/262)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/globals.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EAPWF7irViI4MNhKU:-O5EAPWF7irViI4MNhKV:bf1lwm1) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L35)):*
> ```Python
>     comment: str = '',
> ) -> catalog.Table:
>     """Create a new insertable [`Table`][pixeltable.Table].
> ```

"insertable" is pretty jargon-y from the average user's perspective. "Create a new base Table" would be more consistent with the terminology we've been using in the tutorial docs. 

Once the tutorials are complete, we could link to them from the API docs for additional context.
___
*[`pixeltable/globals.py` line 95 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EAh9U1bSd5ZAp-mqb:-O5EAh9U1bSd5ZAp-mqc:b-8nhrdq) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L95)):*
> ```Python
>     ignore_errors: bool = False,
> ) -> Optional[catalog.Table]:
>     """Create a new derived (not insertable) [`Table`][pixeltable.Table].
> ```

Likewise something like: "Create a new view of an existing Table. The existing Table can either be a base table or an existing view"
___
*[`pixeltable/globals.py` line 179 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EB6QQ8NaphWIUND9w:-O5EB6QQ8NaphWIUND9x:b-g6rus2) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L179)):*
> ```Python
> 
> def get_table(path: str) -> catalog.Table:
>     """Get a handle to a [`Table`][pixeltable.Table] (including views and snapshots).
> ```

Get a handle to an existing `Table` (which can be a base table, view, or snapshot).
___
*[`pixeltable/globals.py` line 240 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBCu_Bbh1vpi0prnc:-O5EBCu_Bbh1vpi0prnd:b-nqoatg) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L240)):*
> ```Python
> 
> def drop_table(path: str, force: bool = False, ignore_errors: bool = False) -> None:
>     """Drop a table or view.
> ```

or snapshot
___
*[`pixeltable/globals.py` line 278 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBFgn3qWc1lXpLd6C:-O5EBFgn3qWc1lXpLd6D:bhoxkpw) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L278)):*
> ```Python
> 
> def list_tables(dir_path: str = '', recursive: bool = True) -> list[str]:
>     """List the [`Table`][pixeltable.Table]s in a directory.
> ```

List the tables, views, and snapshots in a directory.
___
*[`pixeltable/catalog/table.py` line 30 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBIcO1dNjOs3GJ6RZ:-O5EBIcO1dNjOs3GJ6R_:brt9010) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/catalog/table.py#L30)):*
> ```Python
> 
> class Table(SchemaObject):
>     """Base class for tables and views."""
> ```

and snapshots

(I understand that snapshots are a kind of view. But I'm pointing this out b/c I think it's important to be consistent. If we sometimes say "tables, views, and snapshots", and other times say "tables and views", it's going to be confusing, even if "views" technically implies "views and snapshots".)
___
*[`pixeltable/io/globals.py` line 151 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBgPt22NBkIU8OCsz:-O5EBgPt22NBkIU8OCt-:b-5m24m2) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/globals.py#L151)):*
> ```Python
>     ) -> Table:
>     """
>     Creates a new insertable [`Table`][pixeltable.Table] from a list of dictionaries. The dictionaries must be of the
> ```

s/insertable/base/ (here and below)
___
*[`pixeltable/io/pandas.py` line 19 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBtT33xR1e1KpTHfl:-O5EBtT33xR1e1KpTHfm:b-atuzu2) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/pandas.py#L19)):*
> ```Python
>     comment: str = ''
> ) -> pxt.Table:
>     """Creates a new insertable [`Table`][pixeltable.Table] from a Pandas [`DataFrame`][pixeltable.DataFrame], with the
> ```

Wrong link (it's a Pandas dataframe, not Pixeltable)
___
*[`pixeltable/io/pandas.py` line 23 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBzwV3ileELat4qg4:-O5EBzwV3ileELat4qg5:b-c2iy2h) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/pandas.py#L23)):*
> ```Python
>     [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)
> 
>     The column names of the new table will be identical to those in the dataframe, as long as they are valid
> ```

Even in the Pandas docs I have never seen the spelling "dataframe" - it's always "DataFrame"

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/262)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/globals.py` line 35 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EAPWF7irViI4MNhKU:-O5KVwob2CAPw4TPPlM5:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L35)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

"insertable" is pretty jargon-y from the average user's perspective. "Create a new base Table" would be more consistent with the terminology we've been using in the tutorial docs. 

Once the tutorials are complete, we could link to them from the API docs for additional context.
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 95 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EAh9U1bSd5ZAp-mqb:-O5KVx9y317vTUg8WgRq:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L95)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Likewise something like: "Create a new view of an existing Table. The existing Table can either be a base table or an existing view"
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 179 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EB6QQ8NaphWIUND9w:-O5KVxXyEt54UTvMKvXF:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L179)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Get a handle to an existing `Table` (which can be a base table, view, or snapshot).
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 240 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBCu_Bbh1vpi0prnc:-O5KVyCaChe7nCWb2rOo:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L240)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

or snapshot
</blockquote></details>

Done.
___
*[`pixeltable/globals.py` line 278 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBFgn3qWc1lXpLd6C:-O5KVyVa5qv7MnWsKkzr:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/globals.py#L278)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

List the tables, views, and snapshots in a directory.
</blockquote></details>

Done.
___
*[`pixeltable/catalog/table.py` line 30 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBIcO1dNjOs3GJ6RZ:-O5KVzU6A7ewxGFEpdQ0:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/catalog/table.py#L30)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

and snapshots

(I understand that snapshots are a kind of view. But I'm pointing this out b/c I think it's important to be consistent. If we sometimes say "tables, views, and snapshots", and other times say "tables and views", it's going to be confusing, even if "views" technically implies "views and snapshots".)
</blockquote></details>

Done.
___
*[`pixeltable/io/globals.py` line 151 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBgPt22NBkIU8OCsz:-O5KVzxr4_euE58QPMKd:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/globals.py#L151)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

s/insertable/base/ (here and below)
</blockquote></details>

Done.
___
*[`pixeltable/io/pandas.py` line 19 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBtT33xR1e1KpTHfl:-O5KW0La2RmjuTcZbnrj:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/pandas.py#L19)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Wrong link (it's a Pandas dataframe, not Pixeltable)
</blockquote></details>

Done.
___
*[`pixeltable/io/pandas.py` line 23 at r2](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5EBzwV3ileELat4qg4:-O5KW0fD14XRS4J_OQgK:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/4b0b394a4e477f5be591069a7444bb278a8cc720/pixeltable/io/pandas.py#L23)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Even in the Pandas docs I have never seen the spelling "dataframe" - it's always "DataFrame"
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/262)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 30 at r3](https://reviewable.io/reviews/pixeltable/pixeltable/262#-O5MfC3O2-6R2ctyaOtH:-O5MfC3P-u0iiMRDg2lb:bnqgh90) ([raw file](https://github.com/pixeltable/pixeltable/blob/6df6373eb2e2eab37d9c6b839d45205848bcae7d/pixeltable/catalog/table.py#L30)):*
> ```Python
> 
> class Table(SchemaObject):
>     """Base class for table objects (base tables, views, snapshots)."""
> ```

There are still a few places where we refer to "table objects"; maybe this should say "Base class for table handles". I don't feel super strongly about it

**Review by aaron-siegel — APPROVED** [review]

**Pull request merged**
