### PR TITLE
Use nullable types for defaults on import_csv

### PR DESCRIPTION
**Pull request by aaron-siegel**

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/251)

**Review by mkornacker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/251)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/io/pandas.py` line 75 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4LqgPZ0xNJxPoVM96a:-O4LqgPZ0xNJxPoVM96b:bkhh0np) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L75)):*
> ```Python
> 
> def _df_to_pxt_schema(
>     df: pd.DataFrame, schema_overrides: Optional[dict[str, pxt.ColumnType]], primary_key: Optional[Union[str, list[str]]]
> ```

Brief comment for what's being returned

Also, given that this is an internal function, primary_key should just be list[str] (and the caller can normalize it).

Also, why not make schema_overrides non-optional and let the caller pass a {}. Simplifies the code.
___
*[`pixeltable/io/pandas.py` line 83 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKL1Z1FdKNp0y4d0R:-O4MKL1Z1FdKNp0y4d0S:b41p01u) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L83)):*
> ```Python
>                     f'Column `{pd_name}` specified in `schema_overrides` does not exist in the given `DataFrame`.'
>                 )
>     schema = {}
> ```

Missing type decls
___
*[`pixeltable/io/pandas.py` line 102 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKMev4Vl5OGytpv8q:-O4MKMev4Vl5OGytpv8r:bpp6nc5) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L102)):*
> ```Python
>         if is_pk:
>             pxt_pk.append(pxt_name)
>     return schema, pxt_pk if len(pxt_pk) > 0 else None
> ```

Return an empty list? Makes the code slightly simpler, and create_table() will accept that.
___
*[`pixeltable/io/pandas.py` line 120 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKvIA7NkATIYIF3EO:-O4MKvIA7NkATIYIF3EP:bacx40s) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L120)):*
> ```Python
> 
> 
> def _np_dtype_to_pxt_type(np_dtype: np.dtype, data_col: pd.Series, is_pk: bool) -> pxt.ColumnType:
> ```

Simply nullable instead of is_pk? That's really all this function cares about.
___
*[`tests/io/test_pandas.py` line 12 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MLMf35SlPUn9Td3Kf:-O4MLMf35SlPUn9Td3Kg:boplrnr) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/tests/io/test_pandas.py#L12)):*
> ```Python
> 
> class TestPandas:
>     def test_pandas_csv(self, reset_db) -> None:
> ```

Is there some test case for having a null in a primary key column?

**Review by aaron-siegel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/251)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/io/pandas.py` line 75 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4LqgPZ0xNJxPoVM96a:-O4MylYc1k-tyKl-pUQi:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L75)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Brief comment for what's being returned

Also, given that this is an internal function, primary_key should just be list[str] (and the caller can normalize it).

Also, why not make schema_overrides non-optional and let the caller pass a {}. Simplifies the code.
</blockquote></details>

Done.
___
*[`pixeltable/io/pandas.py` line 83 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKL1Z1FdKNp0y4d0R:-O4MyvdmAQ_S6R024Lqf:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L83)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Missing type decls
</blockquote></details>

Done.
___
*[`pixeltable/io/pandas.py` line 102 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKMev4Vl5OGytpv8q:-O4MywBiBgwbpa5btbyN:bz6h5gq) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L102)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Return an empty list? Makes the code slightly simpler, and create_table() will accept that.
</blockquote></details>

Done. I also realized that the primary key translation logic was bogus b/c it failed to preserve order of the key columns. Fixed that too.
___
*[`pixeltable/io/pandas.py` line 120 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKvIA7NkATIYIF3EO:-O4Mz2OB0zTR8iOlmdeJ:b-wqgfh9) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L120)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Simply nullable instead of is_pk? That's really all this function cares about.
</blockquote></details>

Ok, done. Although the error messages have to say something about the primary key in order to be really useful.
___
*[`tests/io/test_pandas.py` line 12 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MLMf35SlPUn9Td3Kf:-O4Mz9SHDVX4J7a-jiIg:b-8b11j9) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/tests/io/test_pandas.py#L12)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Is there some test case for having a null in a primary key column?
</blockquote></details>

Added

**Review by mkornacker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/251)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/io/pandas.py` line 120 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/251#-O4MKvIA7NkATIYIF3EO:-O4N53ii33DDWJAv9QM8:bcn3o5u) ([raw file](https://github.com/pixeltable/pixeltable/blob/743379522a96e0ba36163e4ba60bc3050a111465/pixeltable/io/pandas.py#L120)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Ok, done. Although the error messages have to say something about the primary key in order to be really useful.
</blockquote></details>

Ah, right.

**Pull request merged**
