### PR TITLE
Rag demo

### PR DESCRIPTION
**Pull request by mkornacker**

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/201)

**Comment by pierrebrunelle** [comment]
Looks great. Can you add the Colab and Kaggle links at the top of the notebook

[Kaggle](https://kaggle.com/kernels/welcome?src=https://github.com/pixeltable/pixeltable/blob/master/docs/release/tutorials/rag-demo.ipynb)
[Colab](https://colab.research.google.com/github/pixeltable/pixeltable/blob/master/docs/release/tutorials/rag-demo.ipynb)

**Comment by aaron-siegel** [comment]
Comments:
- Add "Open in Kaggle / Open in Colab" (you can cargo-cult them from another demo notebook)
- Remove `data_dir = Path('~/pt-test/rag-docs').expanduser()` from the top of the notebook
- I guess `import_excel` doesn't work with URLs? We should fix that
- Where did the list of questions come from? Are they the questions from A&M?
- Remove spurious empty cell at the bottom
- Might be good to add a paragraph of concluding remarks with suggestions for other things to explore?

**Comment by mkornacker** [comment]
Done.

**Comment by mkornacker** [comment]
re Aaron's comments:
- did 1, 2, 5
- questions are from Pierre
- re concluding paragraph: let's do that later, I just want to get this out
so Sam can play with it

**Review by aaron-siegel — APPROVED** [review]

**Comment by pierrebrunelle** [comment]
**Just add this boilerplate at the end:**

Congratulations! You've reached the end of the tutorial. Hopefully, this gives a good overview of the capabilities of Pixeltable, but there's much more to explore. As a next step, you might check out one of the other tutorials, depending on your interests:

[Object Detection in Videos](https://pixeltable.readme.io/docs/object-detection-in-videos/)
[RAG Operations in Pixeltable](https://pixeltable.readme.io/docs/rag-operations/)
[Working with OpenAI in Pixeltable](https://pixeltable.readme.io/docs/working-with-openai/)

**Pull request merged**
