### PR TITLE
Initial support for similarity search

### PR DESCRIPTION
**Pull request by mkornacker**
Includes:
- new expr type SimilarityExpr
- ColumnRef augmented to produce SimilarityExprs
- IndexBase.search_clause() and implementation for EmbeddingIndex

To do:
- implementation of a TextSearchIndex to validate the IndexBase interface

### CODE REVIEW

**Comment by aaron-siegel** [comment]
This change is [Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/135)

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/135)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/catalog/table.py` line 485 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCMChG8WH5nJJ1cTfL:-NwCMChG8WH5nJJ1cTfM:brz04wz) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/catalog/table.py#L485)):*
> ```Python
>     ) -> None:
>         """Add an index to the table.
>         Args:
> ```

List `metric` here along with the supported options
___
*[`pixeltable/exprs/column_ref.py` line 66 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCMSG75wcnvDA_D639:-NwCMSG75wcnvDA_D63A:bsz4wwh) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/column_ref.py#L66)):*
> ```Python
>         return super().__getattr__(name)
> 
>     def __mod__(self, other: Any) -> Expr:
> ```

Is there a precedent for using % for similarity (e.g., are there other libraries/contexts where that notation is used)?

If not, I would suggest we avoid it here and just use `t.col1.similarity(t.col2)`. Overloading operators for bespoke operations is seldom wise; it can make code hard to read and semantics confusing. It's even worse when it's munged with something else (in this case, modulus). By contrast, `t.col1.similarity(t.col2)` is crystal-clear.

Another argument for avoiding % is that we can always introduce it later as a synonym for `similarity`, whereas if we introduce it now and come to regret it, we'll be stuck.
___
*[`pixeltable/exprs/expr.py` line 317 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCNrjG-i4F464XoRFM:-NwCNrjG-i4F464XoRFN:bhuk8a7) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/expr.py#L317)):*
> ```Python
> 
>     def _equals(self, other: Expr) -> bool:
>         return True
> ```

This is sufficiently unexpected that it at least needs a comment: what is the purpose of `_equals` and why is its default `True`?
___
*[`pixeltable/exprs/similarity_expr.py` line 27 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCOUPF-UiF7Pli76OC:-NwCOUPF-UiF7Pli76OD:b-degrd7) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/similarity_expr.py#L27)):*
> ```Python
>             raise excs.Error(
>                 f'Column {left.col} has multiple indices; use the index name to disambiguate, '
>                 f'e.g., "{left.col}.<index-name> %% ..."')
> ```

Enclose code in string with backticks rather than double-quotes?
___
*[`pixeltable/exprs/similarity_expr.py` line 31 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCOMa66H9OP-3JvPoc:-NwCOMa66H9OP-3JvPod:bbx45mq) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/similarity_expr.py#L31)):*
> ```Python
> 
>     def __str__(self) -> str:
>         return f'{self.components[0]} %% {self.components[1]}'
> ```

I'd prefer `{self.components[0]}.similarity({self.components[1]})` here; see preceding comment
___
*[`pixeltable/func/function.py` line 56 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCP57Z1b743Br26tj_:-NwCP57Z1b743Br26tja:b4203e4) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/func/function.py#L56)):*
> ```Python
>     def exec(self, *args: Any, **kwargs: Any) -> Any:
>         """Execute the function with the given arguments and return the result."""
>         pass
> ```

I think `...` is preferred to `pass` for an abstract method
___
*[`pixeltable/index/base.py` line 40 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCPNdh1Ja1LJJhHXXM:-NwCPNdh1Ja1LJJhHXXN:bnbpvvy) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/index/base.py#L40)):*
> ```Python
>     def search_clause(self, val_column: catalog.Column, item: Any) -> sql.ClauseElement:
>         """Return a sqlalchemy clause that corresponds to "<indexed col> % <item>" """
>         pass
> ```

Use `...` instead of `pass`
___
*[`pixeltable/tests/test_index.py` line 37 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCPtdx2aPrKVKGXnrz:-NwCPtdx2aPrKVKGXns-:bvyynjg) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/tests/test_index.py#L37)):*
> ```Python
>         _ = img_t.select(img_t.img.similarity(img)).collect()
>         _ = img_t.select(img_t.img, img_t.img % img).order_by(img_t.img % img).collect()
>         pass
> ```

Spurious `pass`

**Review by mkornacker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/135)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @aaron-siegel)

___
*[`pixeltable/catalog/table.py` line 485 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCMChG8WH5nJJ1cTfL:-NwKVmzG0iAVjtEGz7E8:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/catalog/table.py#L485)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

List `metric` here along with the supported options
</blockquote></details>

Done.
___
*[`pixeltable/exprs/column_ref.py` line 66 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCMSG75wcnvDA_D639:-NwKVuC00JgrxVXPiZ7i:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/column_ref.py#L66)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Is there a precedent for using % for similarity (e.g., are there other libraries/contexts where that notation is used)?

If not, I would suggest we avoid it here and just use `t.col1.similarity(t.col2)`. Overloading operators for bespoke operations is seldom wise; it can make code hard to read and semantics confusing. It's even worse when it's munged with something else (in this case, modulus). By contrast, `t.col1.similarity(t.col2)` is crystal-clear.

Another argument for avoiding % is that we can always introduce it later as a synonym for `similarity`, whereas if we introduce it now and come to regret it, we'll be stuck.
</blockquote></details>

Done.
___
*[`pixeltable/exprs/expr.py` line 317 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCNrjG-i4F464XoRFM:-NwKXKWH6tR0gicfW5Sg:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/expr.py#L317)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

This is sufficiently unexpected that it at least needs a comment: what is the purpose of `_equals` and why is its default `True`?
</blockquote></details>

Done.
___
*[`pixeltable/exprs/similarity_expr.py` line 27 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCOUPF-UiF7Pli76OC:-NwKXTpv3AoKPh4WHYhX:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/similarity_expr.py#L27)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Enclose code in string with backticks rather than double-quotes?
</blockquote></details>

Done.
___
*[`pixeltable/exprs/similarity_expr.py` line 31 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCOMa66H9OP-3JvPoc:-NwKXjmJ8Hi51cIJRlGZ:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/exprs/similarity_expr.py#L31)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I'd prefer `{self.components[0]}.similarity({self.components[1]})` here; see preceding comment
</blockquote></details>

Done.
___
*[`pixeltable/func/function.py` line 56 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCP57Z1b743Br26tj_:-NwKY8NsBkidKLfkszTY:b-n5ozo9) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/func/function.py#L56)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

I think `...` is preferred to `pass` for an abstract method
</blockquote></details>

Chatgpt thinks otherwise
___
*[`pixeltable/tests/test_index.py` line 37 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCPtdx2aPrKVKGXnrz:-NwKbu_k7j54g2mVLi_x:b-896fix) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/tests/test_index.py#L37)):*
<details><summary><i>Previously, aaron-siegel (Aaron Siegel) wrote…</i></summary><blockquote>

Spurious `pass`
</blockquote></details>

Done.

**Review by aaron-siegel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pixeltable/pixeltable/135)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/func/function.py` line 56 at r1](https://reviewable.io/reviews/pixeltable/pixeltable/135#-NwCP57Z1b743Br26tj_:-NwVVfV7E2JqZmmiKpXj:bt67qy8) ([raw file](https://github.com/pixeltable/pixeltable/blob/dc6504488f826d37cb6456cbc86929170b76ea23/pixeltable/func/function.py#L56)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

Chatgpt thinks otherwise
</blockquote></details>

Hmm. I consulted Fluent Python, and he actually recommends doing neither! According to Ramalho best practice for abstract methods is just a docstring:

```
    @abc.abstractmethod
    def exec(self, *args: Any, **kwargs: Any) -> Any:
        """Execute the function with the given arguments and return the result."""
```

I kind of like that!

**Review by aaron-siegel — APPROVED** [review]

**Pull request merged**
